go.mod, go.sum
Includes:
- Improvements to type name generation especially for response types
- Add support for simple string request/response bodies
=> chore: update openapi-generation lib to v0.2.0

go.mod, go.sum, internal/sdkgen/sdkgen.go, internal/validation/openapi.go
Needed to remove refs to `GetOrderedErrorString` as well since that was removed in the lib-openapi refactor
=> fix: enable additionalProperties override to false

cmd/generate.go, cmd/validate.go
Methods containing these changes are set as the `RunE` property of cobra command which has the following signature:
```
func(cmd *Command, args []string) error
```
So for now just returning the first error since these were modified in `openapi-generation` to return `[]error`. FYI @TristanSpeakEasy I think this may be why we had `GetOrderedErrorString` util method before?
I'm sending this PR just to fix the CLI asap but will create a linear ticket to look in to this more thoroughly.
=> fix: return single error when required for runE option

README.md
In Markdown `[foo.com]()` doesn't link to `foo.com`, it creates a link to the current page, kinda like `.`, so this link that was supposed to point to the app instead pointed to [this non-existent page](https://github.com/speakeasy-api/speakeasy/blob/main) on GitHub. 
Fixed by adding the URL into the `()` as well.
=> fix: broken link to `app.speakeasy.dev`

README.md, cmd/validate.go
Allow users to run `speakeasy validate ... ` without login to Speakeasy platform
=> feat: allow validation command to run without user auth

Makefile, cmd/docs/main.go, internal/docs/docs.go
This is a prerequisite to setting up automation for generating the docs for the CLI reference in the docs site.
It also automates what was previously a manual step of copying the .md files from this repo to the speakeasy-registry repo and manually updating all the links.
=> docs: add document generation for doc site

internal/utils/interactiveexec.go
Fixes this problem with duplicate label in prompt UI
Unfortunately you can't get rid of a space for the label entirely without forking promptui or creating a pretty involved custom wrapper for how it writes output. Not worth it right now.
=> fix: duplicate label interactive mode

README.md
This fixes broken links to the Speakeasy docs site in the generator's README.
=> fix: documentation links in README.md

cmd/root.go, cmd/suggest.go, cmd/validate.go, go.mod, go.sum, internal/suggestions/client.go, internal/suggestions/utils.go, internal/validation/openapi.go
A sample CLI that communicates with downstream speakeasy API and LLM server.
Normal Testing (CLI)
1. Make sure you have OPENAI_API_KEY set.
2. go run main.go validate openapi --schema openapi-invalid.yaml --fix
Testing with Local API
Local Testing
cd speakeasy-registry (API)
1 Run local registry API
2. Make docker-llm (wait until Chroma is up to continue, you should see Uvicorn running on http://0.0.0.0:8000)
3. export SPEAKEASY_SERVER_URL=http://localhost:35290
=> feat: add LLM suggestions to CLI

internal/merge/merge.go
Will write a test soon, but I tested this locally to ensure it enables `speakeasy merge` to run successfully with local file lookup. The problem is that this CLI command will run from the wrong context on Prove's `generate` step in the action. I would prefer to release this in conjunction with https://github.com/speakeasy-api/sdk-generation-action/pull/35 to test and unblock Prove asap before adding to `merge_test.go`.
=> fix: merge supports local lookups

internal/sdkgen/sdkgen.go
A recent permission change resulted in incorrect permissions for scripts and some other files. This change reverts to the previously incorrect behavior until a better fix can be put into place in a few days.
=> fix: revert recent permission change temporarily

cmd/validate.go, internal/validation/openapi.go
Will disentangle in near future (ie. not have suggest and validate both run `validate.ValidateOpenAPI`).
Just want to get this fix in so when max-suggestions is applied, we don't fail the suggest action even if there are still >0 validation errors remaining in document.
=> fix: dont fail if max-suggestions applied

internal/suggestions/fileFormatter.go
Could definitely benefit from having more unit tests in suggest portion of CLI: https://linear.app/speakeasy/issue/SPE-1995/unit-tests-for-suggest-portion-of-cli
Making this fix quickly for now to see if we can't get some suggest results for customer specs by EOD
=> fix: preserve empty arr instead of converting to null

go.sum, internal/log/log.go, internal/suggestions/client.go, internal/suggestions/fileFormatter.go, internal/suggestions/suggest.go, internal/suggestions/suggestions.go
This PR makes the CLI output validation errors with the correct line number according to the original file type for `suggest`. Currently, if we run suggest on a YAML file, the `suggest` output will show the line number from the JSON conversion since that's the file type we're operating on in the agent loop. We need the output to reflect the original file type so the `finalize` stage of the action can use this for creating PR comments, but the agent can continue to work off the JSON conversion.
=> feat: enable PR comments on line numbers

install.sh
Noticed that install.sh does not correctly set +x perms on my Linux laptop. This fixes the problem.
=> fix: ensure executable permissions on install

cmd/generate.go, go.mod, go.sum, internal/usagegen/usagegen.go
Fixes SPE-1979
Adds on demand usage snippet generation to our CLI
Example by operation-id
speakeasy generate usage -s ./test.yaml -l go -i usageExamplePost
Example by namespace
speakeasy generate usage -s ./test.yaml -l go -n server
Example write to file
speakeasy generate usage -s ./test.yaml -l go -i usageExamplePost -o out.txt
Example formatted dir
speakeasy generate usage -s ./test.yaml -l go -i usageExamplePost -o ./out
=> feat: generated usage snippets in CLI

cmd/validate.go, internal/validation/openapi.go
Adds `--max-validation-errors` and `--max-validation-warnings`. This is to support adding this option to our generation action generation to avoid hitting `$GITHUB_STEP_SUMMARY` limits in large automatically generated specs.
=> feat: add limit options to validation

cmd/validate.go, internal/suggestions/suggestions.go
Go ahead and apply 1000 default to the CLI. This allows the fix to go through without needing an action update. When we release the next version of the action, we can make this default to 0 again, if we like
=> fix: make 1000 msgs global default

go.mod, go.sum
* support unions (oneOf) containing bigint and decimal members
=> fix: release Go unions hotfix

go.mod, go.sum
External dependency for openapi overlays is upgraded to support external reference resolution via libopenapi v0.12.1 indexer.
=> feat: support external references in openapi overlays

cmd/overlay.go, go.mod, go.sum
* Makes overlay generation (via spec comparison) work better. Test cases strengthened.
* Makes overlay apply work with arrays
* Makes the order of yaml map content be preserved
* Allows for merging in of $ref nodes via not resolving recursively: the speakeasy merge tool should be now be used to merge full openapi specs
=> feat: openapi-overlays v0.3.0 (preserve order)

cmd/generate.go, internal/usagegen/usagegen.go
This solves two problems
1. Generation now does not allow "" to be passed as an out dir.
2. For usage snippet generation the out dir is not necessarily tied to where the gen.yaml config is when it's used in things like codespaces or potentially customers use it in docs areas. We should allow it to be an optional argument. We might rework this anyways with new workflow file developments.
=> feat: optional config path for usage snippet generation

go.mod, go.sum
[PR#813](https://github.com/speakeasy-api/openapi-generation/pull/813)
Prevent selecting all available operations for `SDK Example Usage` section and `USAGE.md`
=> fix: prevent selecting all usage snippets for SDK Example Usage section

cmd/merge.go, internal/interactivity/interactiveexec.go
Three fixes:
- interactive mode handles array flags properly
- interactive mode properly skips optional flags if there aren't any
- logLevel flag properly hidden in interactive mode
=> fix: improve merge interactive mode

cmd/api.go, cmd/docs.go, cmd/proxy.go, internal/interactivity/interactiveexec.go
Uses cobras existing construct to hide non-relevant commands from interactive mode
Next Steps
- Try to enable custom ordering of commands (should be doable)
- Deprecate inactive commands (docs we can definitely deprecate)
=> feat: hide non relevant commands from interactive mode

cmd/generate.go, cmd/overlay.go, cmd/root.go
Controlling ordering is actually not too difficult. Cobra's interface of overriding exported `EnableCommandSorting` is a little weird, but this is the way you do it.
=> feat: preserve order for CLI commands

cmd/configure.go, cmd/quickstart.go, prompts/sources.go, prompts/statemappings.go, prompts/targets.go, prompts/utils.go
Adjustments to streamline quickstart
- Autofill source name and target name
- Only prompt for authentication if remote URL fetch doesn't succeed
- Optionally provide schemaURL as an argument
- Optionally provide target type as an argument
=> feat: quickstart streamlining

cmd/configure.go, internal/charm/utils.go, internal/utils/utils.go, prompts/targets.go
Sets up configure new target. This allows us to optionally add a new target to an existing workflow file. We will also enforce that the user sets an output directory for any existing defined target.
=> feat: configure new target

.gitignore, cmd/configure.go, cmd/generate.go, cmd/quickstart.go, cmd/root.go, cmd/run.go, cmd/validate.go, go.mod, go.sum, internal/interactivity/interactiveexec.go, internal/model/command.go, internal/model/flag.go
Goal here is to improve and standardize the way we define commands for the CLI
This allows us to make our commands more consistent with less boilerplate. For example, we now don't need to remember to add `PreRunE: interactivity.GetMissingFlagsPreRun` to every command
=> feat: Move main CLI commands to new interface

cmd/configure.go, prompts/configs.go, prompts/targets.go
This allows us to use `speakeasy configure targets` on an existing target. We will pull in the targets current values and populate them into the CLI form so a user could theoretically click through without any modification. Any changes we will pull back into the workflow and config file.
Next steps here is making `speakeasy configure` have more robust gen.yaml config prompts than `speakeasy quickstart` pulling in all relevant language specific configs and more generation configs.
=> feat: configure for an existing target

cmd/quickstart.go, internal/charm/formModel.go
1. Quickstart cannot be used on an existing legacy SDK
2. Fixes ctrl-c so it always fully exits the program from huh form
Context Here
https://speakeasyapi.slack.com/archives/C0698C9K4NL/p1707240014263139
=> fix: quickstart not used on existing SDK + fix ctrl-c

cmd/configure.go, cmd/quickstart.go, prompts/sources.go, prompts/targets.go, prompts/utils.go
We will allow speakeasy configure to support legacy SDK targets that do not have a workflow file. As part of running speakeasy configure on these repos we will build up a workflow file.
=> feat: support legacy sdk configurations in configure

cmd/quickstart.go, cmd/run.go, internal/run/run.go, internal/run/workflowCliVisualizer.go, internal/run/workflowMermaidVisualizer.go, internal/run/workflowTracking.go
Adds support for a "skipped" status when rendering workflows, and skips validation during `run` if we've already validated
=> feat: skip validation if already run

internal/run/run.go
Interactive Run as creating a fresh context object meaning the SDK context necessary for CLI Event tracking and access checks wasn't working.
=> fix: preserve context interactive run

cmd/overlay.go
Unforunately can't use -o shorthand because we use that for the overlay
=> feat: out flag for overlay apply

cmd/configure.go, cmd/quickstart.go, cmd/run.go, internal/charm/formModel.go, internal/interactivity/listSelect.go, internal/interactivity/multiInput.go, internal/interactivity/tabs.go, prompts/configs.go, prompts/sources.go, prompts/targets.go
We were seeing some instances of a stolen cursor when using ctrl+c in terminals like iterm. I believe this is because we were exiting early from the tea model. By default these models do not return an error on ctrl+c and they don't exit the program. The sort of swallow ctrl+c leaving you to implement intended behavior.
Rather than using using os.exit(0) immediately when we read the keystroke we need to gracefully exit the tea model and then exit the program.
Look at this change for the most simple example
https://github.com/speakeasy-api/speakeasy/pull/491/files#diff-18db6ef98884f0795575414883005156de964fe5d2a7231a15b09fe132a32015
=> fix: stolen cursor in charm usage

go.mod, go.sum
[SPE-2919](https://linear.app/speakeasy/issue/SPE-2919/issue-with-ruby-sdk-generation-in-speakeasy-due-to-mixup-between)
[PR#1058](https://github.com/speakeasy-api/openapi-generation/pull/1058)
This PR allows the use of`x-speakeasy-server-id` to name servers as well as server variables in Ruby
=> fix: named servers handling in Ruby (x-speakeasy-server-id)

internal/sdkgen/sdkgen.go
Looks like loadconfig now requires a target list. This broke compilation in speakeasy validate.
Not actually sure we should pass all target types here.
=> fix: compilation error load config

internal/log/log.go
This change replaces an explicit `panic()` in the custom logger when serializing zap fields of unknown type with an attempt at json-encoding the underlying value. If this fails then the log field is set to the string `"<skipped>"`.
Fixes SPE-3090
=> fix: json-encode zap fields in log messages

internal/charm/utils.go
Supports autocomplete for relative paths of the current directory.
filepath.join will always remove the ./ when working with the current working directory.
=> feat: current directory autocomplete

prompts/sources.go
Map github files to raw github files that are readable during quickstart/configure. This is something we used to do on the webapp, but now there is no uploading specs in the webapp anymore.
=> feat: map github files

internal/usagegen/usagegen.go
Usage snippets like the following were not working
=> fix: regex match for usage snippets

internal/run/run.go
Fixes two issues with running workflow for sources only
- We were not able to handle remote overlay files
- We were not cleaning up the temp dir on success when running sources only
We were not supporting applying multiple overlays for 1 source in a workflow. This would always fail. That's because we need to write each overlay apply to a temporary document and then use that as an input for the next Apply. We were trying to keep a running document which was not working.
=> feat: fixes for source applies

internal/log/log.go, internal/run/criticalWarnings.go, internal/run/run.go
https://linear.app/speakeasy/issue/SPE-3159/speakeasy-run-in-interactive-mode-does-not-log-skipped-operations
=> feat: visualize critical warnings [SPE-3159]

go.mod, go.sum
Addresses SPE-3039 + SPE-3163
This PR introduces conventional namespaces in C#/Unity following [microsoft's guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces).
For example, when setting the following parameters in your `gen.yaml`: 
```
company: Company
product: Product
packageName: My.Company.Product
```
the root namespace will be set to `Company.Product` and the NuGet PackageID to `My.Company.Product`.
If `packageName` is not provided, the PackageID will match the root namespace instead.
=> feat: introduce conventional namespaces C#/Unity

cmd/quickstart.go, cmd/sample_openapi.yaml, go.mod, internal/run/run.go, prompts/sources.go, prompts/statemappings.go
* Offer to use a hand curated Petstore Open API spec which produces a nice looking SDK
* Writes the sample openapi spec in the parent directory of the new target (fallsback to inside the target directory if that fails)
* Defaults new target directory name to `{{kebab-sdk-name}}-{{targetName}}`
https://github.com/speakeasy-api/speakeasy/assets/1690659/d27dbc04-2735-4c84-be56-2b734f0ea838
=> feat: offer sample OpenAPI Document

internal/validation/config.go, internal/validation/customConfigValidators.go
This is borderline impossible to achieve with a regex, so I've unfortunately had to go with this option
Example output:
```
ERROR    field 'additionalDependencies' is invalid: extra dependency dev is invalid: dependency pytest must start with one of: ==, >=, >, ~=, <, <=, !=, ===. Field description: Specify additional dependencies to include in the generated setup.py file```
=> feat: properly validate python additional deps

internal/run/run.go
During quickstart "the current directory" is not helpful as we set the working directory to be the outDir inside quickstart.go, rather be explicit especially as all the history of responses of the forms are cleared from the buffer.
=> chore: show absolute path in run visualization

prompts/configs.go, prompts/utils.go
While we are not actively supporting managed SDK docs we should not have it in quickstart, it brings too much confusion.
=> feat: omit docs from quickstart

cmd/generate/generate.go, cmd/run.go
Even though run does more than just generate SDKs I think new users looking at our CLI through help or interactive mode miss the point that they should be using this to generate.
=> feat: clarify run and generate descriptions

.gitignore, cmd/root.go, integration/main_test.go, integration/resources/codeSamples.yaml, integration/resources/spec.yaml, integration/utils.go, integration/workflow_test.go
This could be a fairly easy way to write integration tests for the CLI. We basically execute CLI commands directly from the root level with each command going in it's own temp subdirectory. Writing tests this way would be very easy.
There's one largish drawback here. These tests have to executed in serial because we have to deal with changing the working directory. I'm not sure if there's a great way around this if we want to really test the CLI as if we are executing individual commands.
There are options to mock os operations, such as [aefro](https://github.com/spf13/afero). The problem is you have to replace usage of the os package with it. We use that not just in the CLI but also in all of this underlying separate modules sdk-gen-config, openapi-generation, etc. I'm just not sure …
=> feat: sample integration testing cli

.github/workflows/validate.yml, integration/main_test.go, integration/resources/codeSamples-JSON.yaml, integration/resources/part1.yaml, integration/resources/part2.yaml, integration/workflow_test.go
Adds basic CLI integration testing to PRs
- Sets up Integration tests run on PR operations
- Adds some additional tests to cover merging, JSON specs
- Creates the basic framework for splitting up tests across multiple jobs to ensure fast speeds (remember tests must be run in serial for each runner). Right now we have two test groups.
=> feat: add integration tests to CI

cmd/quickstart.go
Sets a default out dir for terraform specific validation that will always be valid.
=> feat: terraform specific out dirs for quickstart

internal/model/command.go
=> fix: rely on --pinned flag

internal/run/run.go
This change fixes an issue where document localization was failing because the document path, used as input to the localizer, was constructed incorrectly.
=> fix: remove unnecessary filepath.Join call

integration/workflow_test.go, internal/run/run.go
We don't need to error here. Might want to add back in when the registry flag is off
=> fix: don't error on missing source lock

go.mod, go.sum, internal/overlay/overlay.go, internal/suggestions/example_experiment.go, pkg/merge/merge.go
When producing an overlay by Compare, we no longer generate an `extends` line that references the original file's location.
This is because it's never actually being useful, as we always pass in a specific file location for an overlay to run against
=> chore: remove overlay extends

go.mod, go.sum, internal/download/download.go
Finds the root openapi file for workflows correctly via the annotation that was set during bundling.
Before we were just doing a best effort thing that wouldn't always work. One caveat of this is that registry bundles before this annotation started being [set](https://github.com/speakeasy-api/speakeasy/pull/641) won't work. I think that is fine, since the product hasn't been released yet.
=> feat: find root openapi file from annotation

internal/model/command.go, internal/utils/utils.go
There is a bug in version pinnning that would cause failures if the target id had a space in it. This fixes that
=> fix: support spaces in target names

internal/download/download.go, internal/run/run.go
This change updates the workflow runner to better determine the file extensions of documents. We'll attempt to:
- use the extensions of the output document if one is specified
- or, if it's a remote document
- fallback to the extension of document's URL path if it's remote
- or, fallback to sniffing the `content-type` header
- or, finally fallback to `.yaml`
=> fix: support documents with unknown extensions

internal/run/run.go
This change fixes a regression that result in the workflow executor ignoring the final result of applying overlays in subsequent workflow steps including SDK generation.
=> fix: capture overlay output path as final doc path

cmd/openapi.go, go.mod, go.sum, internal/changes/openapiChanges.go, internal/reports/reports.go, internal/run/run.go, internal/validation/openapi.go, registry/utils.go
* Upgrade SDK-gen-config - safely parses registry URLs correctly
* Checks if the workspace of registry URL matches the currently authenticated workspace
* Fixes OpenAPIDiffReportDigest being written even for linting reports
* Fixes report digests are only set if upload succeeded
* Upgrade core: populates CLI Event field OpenAPIDifBreakingChangesCount
=> fix: Open API changes CLI events data

go.mod, go.sum, internal/changes/openapiChanges.go
Puts JS / CSS for change report into CDN such that the openapi change bundles are now much, much smaller.
=> chore: smaller openapi change bundles

cmd/quickstart.go, cmd/run.go, internal/run/run.go
Adds the ability to apply tags to speakeasy registry bundles
Example:
speakeasy run --bundle-tag latest --bundle-tag "my-source:main"  
speakeasy run --bundle-tag "latest,release-cut"
=> feat: add registry tagging to speakeasy run

go.mod, go.sum, internal/migrate/migrate.go, internal/run/run.go, prompts/github.go, prompts/sources.go
- When a publishing location isn't provided make sourceID kebab case to make it more likely to succeed
- Backfill a publishing location into the workflow file
=> feat: automatically migrate registry users to source registry location

cmd/configure.go, prompts/github.go
Allows us to support monorepo mode natively in configure github. Typically when you have multiple different targets in the same repo we want to generate and publishing in separate runs and PRs for each target. We separate their files into their own subdirectory of github workflows.
=> feat: natively support monorepo mode in configure github

.github/workflows/validate.yml
This change switches the conventional commit PR title check to use the `amannn/action-semantic-pull-request@v5` action since the current one we use is no longer maintained and in a broken state.
=> fix: switch to amannn/action-semantic-pull-request

internal/run/run.go
If we have a workflow file that has multiple targets generated which all read from the same source we can end up seeing duplicate change summary entries in github. Like [this](https://github.com/speakeasy-api/speakeasy-registry/pull/2210).
This check should allow us to see if we've already computed a changeSummary for this source. If we wanted to get more specific we could do source -> previous revision combination, but I think this could end up getting more confusing.
=> fix: check for duplicate changes summary

go.mod, go.sum, registry/utils.go
Switches feature flags to read from enabled_feature which we will support as an open enum. To merge after deploy
=> chore: perpare for open enum feature flags

cmd/quickstart.go, internal/run/run.go
In quickstart when a valid subset spec cannot be found to pass validation prompt if they would like to retry with a sample spec
=> feat: quickstart sample spec retry

internal/validation/openapi.go
Ideally we would just not return bogus line numbers, but this is a fine band-aid
=> fix: don't panic on bad validation lineNums

cmd/quickstart.go, internal/run/run.go, internal/sdkgen/sdkgen.go
We want to create more of a direct link between the CLI and our SDK UX overview.
- Always print overview links for each SDK target in speakeasy run
- In speakeasy quickstart best effort auto open the overview URL
=> feat: directly link CLI to UX overview

prompts/github.go
Out github action requires publishing secrets to be placed in specific environment variables. We will start setting up workflows files and instructing users to put secrets in those variables rather than leaving variable name open to input.
=> feat: standardize publishing secret names

cmd/configure.go
If we create a new target in a sub directory of an existing repo we need to make sure that the config file for that target is written into the correct repo. To do this we create an empty gen.yaml before writing the config. If we don't do this saveConfig will find an existing config file in the root directory and write things in the wrong place.
=> fix: nested config directories

prompts/configs.go
Sets a sensible default for the terraform provider name based on the SDK Class Name. Current openapi-generation default is not valid.
=> feat: sensible default for terraform provider name

internal/overlay/overlay.go, internal/validation/openapi.go
[Libopenapi sniffs whether a document is JSON or YAML based on whether the document starts with { and ends with }](https://github.com/pb33f/libopenapi/blob/f27d57aab08d3c63b47a22a67665c909b773391c/datamodel/spec_info.go#L71). It turns out that you can have a valid YAML document which starts with { and ends with } which has lead to a valid document failing validation. This workaround detects this edge case and reformats the document before validating if needed.
=> fix: validation of YAML files fail if they look like JSON

internal/run/run.go
A common case which I have hit
* Run `speakeasy run` in workspace 1
* Switch directory and run `speakeasy run` ends up pushing bogus registry entries to workspace 1
=> fix: prevent pushing registry entries to the wrong workspace

cmd/quickstart.go, cmd/run.go, internal/run/run.go
Allow a forced version to be passed in to speakeasy run. Typically this will be applied via workflow dispatch in github actions
Note: we do not explicitly check things like git releases in the CLI. This is the same behavior as `speakeasy bump` locally the user can supply whatever they want as long as it's a valid SEMVER version.
Things like the UX and GH Actions are what check against previous version see [here](https://github.com/speakeasy-api/sdk-generation-action/blob/main/internal/actions/runWorkflow.go#L74).
=> feat: supply sdk version in generation run

cmd/configure.go
Previously, the URL returned in the developer instructions would 404, e.g.
```
│ • Setup a Speakeasy API Key as a GitHub Secret - https://app.speakeasyapi.dev/workspaces/clxvz22lp00003b6jplb1ix37/apikeys
```
Now the URL returned is correct:
```
│ • Setup a Speakeasy API Key as a GitHub Secret - https://app.speakeasyapi.dev/org/playground-wnq/playground-testing/settings/api-keys
```
=> fix(configure): GitHub Secret instructions for workspace API Key URL

internal/workflowTracking/workflowTracking.go
=> chore: cleaner failure state on workflowTracking

.github/workflows/release.yml, .goreleaser.yaml, prompts/terraform_release.yaml
Reference: https://goreleaser.com/blog/goreleaser-v2/#upgrading
Reference: https://github.com/goreleaser/goreleaser-action/releases/tag/v6.0.0
It is also possible to set up GitHub Actions to run `goreleaser check` when GoReleaser configurations change, but that can be considered outside these minor updates.
```console
$ goreleaser --version
____       ____      _
/ ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
\____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com
GitVersion:    2.0.1
GitCommit:     684c1805864e5f29acc204e34e1770eb74918d15
GitTreeState:  clean
BuildDate:     2024-06-11T01:45:52
BuiltBy: …
```
=> chore: Updates for GoReleaser v2

cmd/overlay.go, internal/overlay/overlay.go, internal/overlay/overlay_test.go, internal/overlay/testdata/base.json, internal/overlay/testdata/base.yaml, internal/overlay/testdata/components.yaml, internal/overlay/testdata/expected.json, internal/overlay/testdata/expected.yaml, internal/overlay/testdata/expectedWrapped.yaml, internal/run/source.go, internal/suggest/suggest.go, internal/utils/utils.go
Fixes several issues:
- Properly outputs JSON if the requested filetype is JSON
- Maintains key ordering when applying overlays
Risk areas:
- Some customers might be expecting the current (wrong) behavior, in which we output json into `.yaml` files
=> feat: support json output for overlays + maintain key ordering

integration/main_test.go, integration/workflow_test.go
Stops changing directory (as it blocks tests running in parallel). Associated changes to propagate a temporary directory.
Marks all integration tests as runnable in parallel
=> chore: fix integration tests and run in parallel

go.mod, go.sum, integration/workflow_test.go, internal/github/github.go, internal/run/source.go
Part of a body of work that will stop SDK flux. Safe to deploy alone -- behind a feature toggle with an environment variable.
Also upgrades to latest openapi-generation version
=> chore: add new change summary form

integration/main_test.go, integration/overlay_test.go, integration/resources/overlay/openapi-overlayed-expected.yaml, integration/resources/overlay/openapi.yaml, integration/resources/overlay/overlay.yaml, integration/utils.go, integration/workflow_test.go, internal/overlay/overlay.go, internal/overlay/testdata/expected.yaml
When we apply an overlay, we lose indentation of the original file.
This sucks, and can in-particular have negative effects because the overlay file uses `|` for multi-line strings.
Underlying issue is https://github.com/go-yaml/yaml/issues/899
Ideally we'd keep indentation through either [migrating to https://github.com/goccy/go-yaml, or discovering the indentation as the document is parsed]. However as a stop-gap we can make the indentation `2` which aligns it with almost all YAML documents we work with and the overlay files we generate. 
This PR implements that stop-gap and adds an integration test for multi-line strings in overlay files.
=> chore: make yaml default indentation 2

.github/workflows/validate.yml, integration/main_test.go, integration/overlay_test.go, integration/utils.go, integration/workflow_test.go
The `matrix` doesn't appear to work right (as it's not running each test group), but we don't need it. This adjusts the target to run `./...` (i.e. all tests) on both ubuntu and windows.
Also fixes up some tests
=> chore: run all tests all the time

internal/run/source.go
When applying overlays, we currently do not respect the output file type. We always output yaml, even if `output` is `spec.json`
=> fix: properly respect workflow output file type (overlays)

README.md, cmd/auth.go, cmd/root.go, cmd/status.go, docs/README.md, docs/status.md, go.mod, go.sum, internal/run/run.go
Reference: https://linear.app/speakeasy/issue/SPE-3840/feature-implement-speakeasy-status-cli-command
Initially provides a user with a visual overview of their current (non-archived) workspace targets using colors and textual formatting. Each target is displayed as a card. Each card has:
- Headline: Target type, target name (if available and meaningful), onboarding status, and latest version
- Alerts: Such as publish failures (with direct link), generate failures (with direct link), and target upgrades (with docs link)
- Information: Publish URL, repository URL, Speakeasy URL, last publish time, last generate time
The cards are sorted with the top-down precedence:
- Errors, then success
- Onboarding status (published, configured, then unconfigured)
- Target type and version (alphabetical: …
=> feat: Introduce status command

cmd/quickstart.go, cmd/run.go, internal/run/run.go, internal/run/source.go, internal/run/workflow.go
Refactors `run` to use the "functional options pattern". This should only be a code hygiene change. Additionally adds a few options to skip certain steps, though these are unused at the moment
=> chore: move to use option func pattern

cmd/auth.go, internal/auth/auth.go, internal/config/config.go, internal/download/download.go, internal/interactivity/hiddenCommands.go, internal/interactivity/interactiveexec.go, internal/interactivity/listSelect.go, internal/interactivity/multiInput.go, internal/interactivity/simpleInput.go, internal/run/source.go, registry/utils.go
This PR makes it easier and safer for admins to work in customer repos.
It adds support for "multi-auth", making `speakeasy auth login` an additive operation:
- You will now be able to download any registry images without switching workspaces. This should reduce the need to authenticate with customer workspaces and thus reduce the risk of accidentally pushing an image to the wrong workspace
- Snapshotting will be skipped (rather than failing) if the target org doesn't match, again reducing the need to authenticate with customer workspaces
=> feat: improve admin CLI dx for registry publishing/downloading

cmd/configure.go, cmd/quickstart.go, cmd/run.go, internal/ask/ask.go, internal/charm/formModel.go, prompts/configs.go, prompts/github.go, prompts/sources.go, prompts/targets.go
For `speakeasy configure publishing`:
- Automatically skip the target selection if there's only one target
- Actually show the keys which control the target multiselect in the keymap
https://linear.app/speakeasy/issue/SPE-3890/bug-speakeasy-configure-publishing-sets-up-all-targets-regardless-of
=> fix: show keymap for configure publishing target selection

prompts/github.go
https://linear.app/speakeasy/issue/SPE-3877/cli-generates-github-action-syntax-which-doesnt-work-for-monorepos
=> fix: release dir path fix

cmd/status.go
Now that the CLI supports multiple authenticated workspaces, use the currently configured default workspace ID when set, rather than the API key. Falls back to the API key workspace ID.
=> feat: Support switched workspace in status command

install.sh
If we don't see a valid tag name, then something went wrong on the GitHub end.
This sets up a 5-attempt retry with a short exponential backoff.
=> chore: retry github releases

cmd/quickstart.go, cmd/run.go, internal/charm/styles/styles.go, internal/log/log.go, internal/log/markdown.go, internal/run/run.go, internal/run/source.go, internal/run/target.go, internal/run/workflow.go, internal/workflowTracking/workflowTracking.go
Output is mostly unchanged, the styling is just simpler to write
- Also slightly refactors the "success summary" message so that it also prints when running with `-o console`
=> feat: support simple markdown rendering in CLI log statements

.github/workflows/validate.yml, cmd/generate/sdk.go, cmd/openapi.go, cmd/run.go, go.mod, go.sum, integration/overlay_test.go, integration/workflow_registry_test.go, integration/workflow_test.go, internal/download/download.go, internal/overlay/overlay_test.go, internal/run/source.go, internal/run/target.go, internal/run/workflow.go, internal/schema/document.go, internal/sdkgen/sdkgen.go, registry/utils.go
* Adds two extra args to `speakeasy run` `--frozen-workflow-lockfile` and `--skip-versioning`
* Adds an admin user pass-through for schema registry entries (these come with Readonly claims on our server). This is important as we'll shortly start using enterprise customer's latest specifications through the schema registry to validate our changes to generation (as opposed to what we do now, which is manually updated snapshots).
* Supports new version of sdk-gen-config, which has stable locations for schema registry + URL downloads
=> chore: add frozen-workflow-lockfile and skip-versioning arguments, alongside making the schema registry stable

integration/workflow_registry_test.go, integration/workflow_test.go, internal/download/download.go
Makes it such that the error in https://github.com/speakeasy-api/speakeasy/pull/868 can't happen again
=> chore: integration test registry interactions

go.mod, go.sum, internal/charm/styles/markdown.go, internal/charm/styles/styles.go, internal/log/log.go, internal/run/minimumViableSpec.go, internal/run/run.go, internal/run/target.go, internal/studio/modifications/overlay.go, internal/studio/studioHandlers.go, internal/transform/filterOperations.go, internal/validation/openapi.go
The most important change here is that it changes the implementation of "minimum viable spec" to create an overlay directly, rather than updating the source then running `overlay compare`
Note: we are no longer running `deleteUnused` as part of MVS, which may result in some extra linting infos for unused things
Needs https://github.com/speakeasy-api/speakeasy-core/pull/77
=> feat: unify MVS with studio modifications overlay

internal/studio/modifications/overlay.go
Slight bug causing MVS overlay file creation to fail
=> fix: minimum viable spec overlay creation

install.sh
https://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06_04
Exponentation not allowed in standard `sh`
=> chore: no exponentiation

internal/transform/cleanupPaths.go, internal/transform/filterOperations.go, internal/transform/filterOperations_test.go, internal/transform/removeUnused.go, internal/transform/transformer.go
Mistral was apparently using this and relying on the fact that it _also_ removed orphans and empty paths
This reintroduces that functionality at the cost of performance.
=> fix: return filterOperations to its original functionality

go.mod, go.sum
Pylon-2914
This PR addresses compilation errors for Formance PHP due to:
- missing imports for error response fields (`flat` responseFormat)
- unused imports for union arrays (`array<mixed>` )
=> fix: missing/unused imports for error fields and union arrays PHP

cmd/configure.go, prompts/github.go
We will now allow customers to do github generations when the .speakeasy workflow is not in the root directory of their repo. 
Although, this will be an uncommon setup we should also allow them to set up these workflow files from `configure github/publishing`. In this case where it is not being run where a workflow file is present they will be asked to provide the directory.
=> feat: non root directory configure github/publishing

.gitignore, .vscode/launch.json, .vscode/tasks.json
Adds a custom debug configuration that allows debugging of the bubbletea application via a headless dlv instance
=> chore: add vscode debug configuration for cli

.vscode/tasks.json
It turns out that we do need the problem matcher in order for the debug task to be configured successfully.
=> chore: add dlv problem matcher

internal/run/source.go, internal/run/target.go
1. No code samples are uploadable when running frozen-lockfile (we don't want to + our regression suite lacks permissions, it errored)
2. Single registry sources lack a registry URI. This caused a panic.
=> chore: fix a few frozen-lockfile edge cases when running regression suite

go.mod, go.sum, prompts/configs.go
Sets a default envVarPrefix in quickstart for supported languages.
https://linear.app/speakeasy/issue/SPE-4026/set-envvarprefix-out-of-the-box-during-quickstart
=> feat: set default env var prefix for supported languages

go.mod, go.sum
https://github.com/speakeasy-api/openapi-generation/pull/1584
This PR prevents newly added `Summary` and `Table of Contents` Readme sections to be templated at the bottom of existing `README.md` files
=> fix: summary and toc readme sections positioning

internal/run/source.go
This suggest UI is outdated (and broken). We shouldn't link to it anymore
=> chore: remove 'improve with ai' link from run output

internal/codesamples/codesamples.go
Stops them rotating all the time on customer repos
=> chore: code samples are ordered

cmd/lint.go, cmd/merge.go, go.mod, go.sum, internal/run/source.go, internal/run/workflow.go, internal/studio/oas_studio.yaml, internal/studio/studioHandlers.go, internal/validation/openapi.go, internal/workflowTracking/workflowTracking.go, pkg/merge/merge.go
**Why:** we were facing laggy editing of the spec file in the studio
**What:** 
* Update openapi-generation to skip unnecessary work when linting. 
* Don't upload linting reports for every run of the studio. The first run of the workflow will upload the linting report as usual but subsequent runs will not upload a report.
* Slightly unrelated, added better "step" when emitting `OnSourceResult`
=> feat: linting performance improvements

prompts/sources.go
We don't need to prompt for an OAS location if the `--schema` arg is passed into quickstart.
Prior code path had the CLI crash
=> chore: fix broken --schema arg

internal/run/run.go
Fixes an [issue](https://github.com/speakeasy-api/speakeasy/pull/901/files#r1747243163) caused by a nil pointer from #901 reported by a customer
=> fix: nil pointer error

go.mod, go.sum, internal/studio/modifications/overlay.go, internal/studio/studioHandlers.go, internal/suggest/suggest.go
Adds support for deduplicating suggestions before upserting the modifications overlay. Also deduplicates the results of Suggest itself based on the existing contents of the overlay if one exists
https://speakeasyapi.slack.com/archives/C07C7QUB53L/p1725655028783219
=> fix: deduplicate suggestions

go.mod, go.sum, integration/workflow_test.go, internal/run/run.go, internal/run/source.go, internal/run/target.go
We faced an incident where a [nil pointer was not checked](https://github.com/speakeasy-api/speakeasy/pull/920) in one case in `runInner`. This refactor introduces a test case which would have caught that case and makes runInner much simpler to read.
=> chore: refactor workflow runInner to be easier to read

cmd/quickstart.go, cmd/run.go, go.mod, internal/ask/ask.go, internal/config/config.go, internal/interactivity/button.go, internal/interactivity/simpleConfirm.go, internal/model/command.go, internal/model/flag/booleanFlag.go, internal/studio/launchStudio.go, internal/studio/studioHandlers.go
Fixes/improvements:
- If we haven't seen a health check 10 seconds after launching the studio, kill the server 
- Don't cleanup until after the studio has run
- Display the nice workflow viz rather than the "console" output
- Skip snapshotting and change reports during studio runs
- Launch studio when:
- There's exactly one source result
- AND We have useful diagnostics
- AND:
- We've just come from quickstart
- OR the user is in `run` but has never seen the studio before
- OR the user is an admin
=> fix: studio: improve cli <-> integration

internal/studio/launchStudio.go
* For the case where the user has to paste the link maybe they end up taking more than 10 seconds
=> fix: increase timeout of studio handler

cmd/quickstart.go
This is so that onboarding users are prompted to add `speakeasy run --watch`
=> fix: add `--watch` to rerun of quickstart

cmd/quickstart.go, internal/git/repository.go
Initialises a new git repository locally at the beginning of quickstart if one doesn't previously exist in the working directory.
=> feat: initialize git repository during quickstart

internal/studio/launchStudio.go
For users like @LukeHagar who use a virtual env to develop locally port forwarding is needed to be able to use the studio. Simply printing a `Listening on ...`, is good enough for clever terminals like VSCode to pick up this message and suggest port forwarding 🥳
=> fix: studio listening message

internal/studio/launchStudio.go, internal/studio/studioHandlers.go
We now output
```
Listening on http://localhost:3333
Opening URL in your browser:  https://app.speakeasy.com/org/speakeasy-self/speakeasy-self/studio/3333#stu-e6e482886b6a4e913a183c61fed1d248
```
They could click on the localhost one so we redirect in that case
=> fix: studio handle clicking on "listening on ..." message

cmd/root.go
Also re-enables showing the update message to speakeasy devs. This has been hidden for a while which means we missed the styling issue for a while
=> fix: Make update prompt readable on all terminals

.goreleaser.yaml
Reference: https://goreleaser.com/deprecations#snapshotnametemplate
Previously during release:
```
• setting defaults
• DEPRECATED: snapshot.name_template should not be used anymore, check https://goreleaser.com/deprecations#snapshotnametemplate for more info
```
=> chore: Update goreleaser configuration for snapshot.name_template deprecation

internal/interactivity/tabs.go
The interactive tabs in the terminal currently try to use unicode box drawings to render active/inactive rounded tabs. Unfortunately for the inactive tabs, the active color spills into the active tab styles (see screenshots). I don't think that it is possible to fix this issue with the current styles with our glyph borders, so I think personally it's nicer if we render a hidden border for the inactive tabs
Before:
After:
=> fix: TUI tab border styles

cmd/run.go, internal/run/source.go, internal/run/workflow.go
We'd like to use the `speakeasy-recommended` ruleset for the studio only. This ruleset includes additional lint rules such as `missing-examples` that we'd like to display in the studio.
=> fix: override rulesets used for watch mode / studio

.github/dependabot.yml
Reference: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/managing-security-and-analysis-settings-for-your-organization#allowing-dependabot-to-access-private-repositories
We can add this instead if we do want to automate them (or if these ignores don't do the trick):
```yaml
registries:
github-private:
type: git
url: https://github.com
username: x-access-token
password: ${{secrets.BOT_REPO_TOKEN}}
updates:
- package-ecosystem: gomod
registries:
- github-private
```
=> chore: Ignore additional private repos in Dependabot for now

.github/dependabot.yml
Reference: https://github.com/speakeasy-api/speakeasy/network/updates/891626743
Even with ignored dependencies, transitive private dependencies can cause access issues for Dependabot. This additional configuration runs the Go module updates with a token that has private repository access and is already shared as an organization-wide Dependabot secret.
=> chore(deps): Additional Dependabot configuration for private repository access

README.md
Stops GitHub from autolinking the target logos which doesn't go anywhere anyway :)
=> fix: readme logos

internal/interactivity/interactiveexec.go
Currently the pflag package automatically sorts flags, which results in the interactive prompts displaying flags alphabetically rather than in the order they were defined in code.
This is particularly annoying for the `speakeasy overlay` command, where `before` and `after` are switched around:
I think this change is probably acceptable across the board, as one can assume that flags are already ordered in a logical manner in the code itself. If anyone can think of a case where the default alphabetical sort is important, then let me know.
=> fix: dont sort cmd flags automatically in interactive prompts

internal/updates/updates.go
Reference: https://linear.app/speakeasy/issue/SPE-4208/bug-cli-update-fails-on-linux-with-differing-filesystems-for-tmp-and
Reference: https://github.com/golang/go/issues/41487
When the CLI is running on Linux, the Linux system has different mounts for home and temporary directories, and the `update` command is called (or the same functionality automatically invoked with other commands), then the CLI can return an `invalid cross-device link` error without updating the executable when using the Go standard library `os.Rename()` function. This change introduces fallback logic to catch that error and manually overwrite the executable while accounting for `ETXTBSY` errors on the running executable.
Reproduction (macOS host):
```console
$ docker run -i -t --privileged --rm ubuntu:24.04
``` …
=> fix: Prevent invalid cross-device link update errors on Linux

cmd/quickstart.go
Fixes the Quickstart command so that the `outDir` is used when initialising a new git repo
https://linear.app/speakeasy/issue/SPE-4197/bug-cli-quickstart-created-git-in-wrong-directory
=> fix: init git repo in outdir

internal/updates/updates.go
Reference: https://pkg.go.dev/os#MkdirTemp
> It is the caller's responsibility to remove the directory when it is no longer needed.
Be kind and rewind!
=> fix: Always clean up temporary directory on updates

cmd/quickstart.go, cmd/run.go, internal/run/workflow.go, internal/studio/launchStudio.go
Removes the numdiagnostics check from "canLaunch". This is really a _should_ launch concept
The effect of this is that `--watch` will open the studio even if there are no diagnostics, when before it would just do nothing
=> fix: allow studio to be launched without diagnostics

cmd/root.go
Hides the big yellow box when working locally - it's not that relevant
=> fix: hide update msg for local dev cli

.github/workflows/documentation.yml, .github/workflows/release.yml, .github/workflows/validate.yml
Reference: https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file
Prevent the need to manually update versions in CI files or otherwise have CI error on Go module version updates.
This change also removes the manual cache: true and actions/cache usage, as its automatic in actions/setup-go:
> The action has a built-in functionality for caching and restoring go modules and build outputs. It uses toolkit/cache under the hood but requires less configuration settings. The cache input is optional, and caching is turned on by default.
=> chore: Update GitHub Actions setup-go to use go-version-file

internal/suggest/errorCodes/errorCodes.go, internal/suggest/errorCodes/errorCodes_test.go, internal/suggest/errorCodes/testData/petstore.yaml, internal/suggest/errorCodes/testData/petstore_expected.yaml
Error-codes suggest doesn't work properly for specs that don't already have a `components.responses` or `components.schemas` section
=> fix: support specs with no responses section for error-codes suggest

prompts/github.go
Populating this is redundant and irrelevant, workflow.yaml determines what versions are used.
=> feat: we should no longer populate speakeasy version in new actions

cmd/quickstart.go, go.mod, go.sum, internal/charm/formModel.go, internal/charm/transformAccessor.go, internal/charm/utils.go, prompts/configs.go, prompts/github.go, prompts/sources.go, prompts/targets.go
On windows, "enter" gets interpreted as a space sometimes. This solves this anywhere we use `cham_internal.NewInput` by using a custom accessor which removes whitespace any time the value is written
=> fix: automagically trim spaces from form input

cmd/run.go, internal/run/source.go, internal/run/workflow.go, internal/studio/studioHandlers.go
Removes specific overriding of rulesets from the CLI code in the case where watch flag is provided 
https://speakeasyapi.slack.com/archives/C0698C9K4NL/p1729078919662769
=> fix: remove ruleset overriding for studio

cmd/status.go, go.mod, go.sum
Restore workspace ID globals in the speakeasy go sdk to fix generate cli events
=> fix: generate cli events

internal/studio/modifications/overlay.go, internal/studio/studioHandlers.go, internal/suggest/suggest.go
https://linear.app/speakeasy/issue/SPE-4404/bug-studio-not-suggesting-additional-fixes-for-newly-added-operations
The actual issue was just a missing `not` in a filter expression. But I took the opportunity to improve how we get suggestions more broadly by pre-filtering operations for which we have suggestions. This speeds up the roundtrip to the LLM (before, we were getting all suggestions then filtering afterwards)
=> fix: better additive method name suggestions

internal/run/target.go
Captures all codesamples logic behind the "blocking/non-blocking" logic instead of just the actual generation part
=> fix: don't block on codesample push failure

go.mod, go.sum
bump speakeasy-core (no public interface changes, just an extra private method for use in our generator)
=> chore: upgrade speakeasy-core

internal/run/target.go
There's a bug currently when codeSamples `output` is unset but the target's `output` IS set. This causes codesamples to fail because it tries to write the output to target.output, which is always a directory
=> fix: codeSamples no output path fix

integration/workflow_test.go, internal/run/source.go
Now we will properly convert to json during `run` if `output: ` has a `.json` extension
https://linear.app/speakeasy/issue/SPE-4451/request-output-in-json-format-instead-of-yaml
=> fix: properly output json in run when requested

cmd/root.go, cmd/testcmd.go, internal/charm/styles/styles.go, internal/env/env.go, internal/model/command.go, internal/sdkgen/sdkgen.go, internal/testcmd/runner.go, internal/testcmd/runner_opt.go
Reference: https://linear.app/speakeasy/issue/GEN-778/feature-speakeasy-test-cli-command
This change introduces an initial `speakeasy test` CLI command, which runs workflow target testing such as `go test` for Go and `vitest` for TypeScript. Its output is similar to the `speakeasy run` CLI command including both an interactive mode with enhanced CLI visualization (unless passing the `--verbose` flag) and non-interactive mode. It will return an error status code if the workflow configuration cannot be discovered, if there are test failures as determined by the target testing, or any other process handling errors. The command should support running in GitHub Actions with appropriate CLI version selection, outputs, and error handling.
Future generator enhancements will enable the command to …
=> feat: Initial test command

cmd/docs/main.go, cmd/generate/generate.go, cmd/lint/lint.go, cmd/quickstart.go, cmd/tag.go, go.mod, internal/config/config.go, internal/docs/docs.go, internal/github/github.go, internal/interactivity/interactiveexec.go, internal/migrate/migrate.go, internal/studio/launchStudio.go, internal/transform/filterOperations.go
The `maps.Keys` and `slices.Contains` functionality has moved into the Go standard library.
=> chore(deps): Remove extraneous golang.org/x/exp dependency

go.mod, go.sum, internal/run/sourceTracking.go
1. Should result in less (no?) duplicates in the registry, as those duplicates emerged from the sourcemap and some random strings in filenames, alongside representing full (abs) filenames. If we have a use-case for this we'll re-add it in a different form.
2. info.version (i.e. the openapi document version) should now be always uploaded into the registry as a tag. This makes public URLs more meaningful
=> chore: do not store sourcemaps, always include openapi info.version as a tag

internal/charm/utils.go, internal/interactivity/simpleConfirm.go, internal/remote/sources.go, prompts/sources.go, prompts/statemappings.go
This PR adds the ability to bootstrap a new target using a pre-existing specification hosted on Speakeasy's registry. The CLI will now show the most recent 5 targets that have been interacted with (based on the CLI event stream).
If there are any recent target candidates in the workspace, then the user will be presented with the option to choose from an existing SDK or create from scratch at the beginning of Quickstart. If there are no previous generations in a workspace, then the existing "new user" flow will be shown where the user can enter a filepath to a spec:
Then selecting from the list of recent SDKs:
(n.b the look and feel of the select list in the 2nd screenshot will change / look much better once the corresponding https://github.com/charmbracelet/huh/pull/424 pr has been …
=> feat: base quickstart on remote existing target

internal/model/command.go
We already have the check above to continue on this type of error
=> fix: use local version on download failure

cmd/openapi/transform.go, integration/resources/formatted.yaml, integration/resources/unformatted.yaml, internal/transform/format.go, internal/transform/format_test.go
This pull request introduces a new command to format OpenAPI documents and includes corresponding tests. The most important changes include adding the `formatCmd` command, implementing the `runFormat` function, and creating tests to ensure the formatting works correctly.
* [`cmd/openapi/transform.go`](diffhunk://#diff-f618debf6dbd5b8b72bdb3a3772aff1757bd578d0810643b6821fb87c7c6f864R5-R17): Added the `formatCmd` command to the `transformCmd` command group, which formats an OpenAPI document to be more human-readable. [[1]](diffhunk://#diff-f618debf6dbd5b8b72bdb3a3772aff1757bd578d0810643b6821fb87c7c6f864R5-R17) [[2]](diffhunk://#diff-f618debf6dbd5b8b72bdb3a3772aff1757bd578d0810643b6821fb87c7c6f864R80-R87)
* [`cmd/openapi/transform.go`](diffhunk://#diff-f618debf6dbd5b8b72bdb3a3772aff1757bd578d …
=> feat: format transform

.github/workflows/release.yml, .github/workflows/validate.yml
Reference: https://github.com/actions/setup-go/issues/495
This improves PR testing from >15 minutes to <5 minutes by using larger runners (in runner group so we can tune them without adjusting workflow configuration) and by disabling setup-go caching on Windows. Previously, it could take up to 10 minutes to download and unarchive the setup-go cache on Windows runners due to an acknowledged issue. While this could potentially introduce transient network issues downloading the Go modules from Google's proxies, those issues are generally pretty rare in my experience. We could alternatively change the module cache environment variables on Windows to point at the second hard drive on the runner, but that seemed more likely to break at some point outside our control. Ideally GitHub will fix the …
=> chore: Use larger runners and disable setup-go caching on Windows for CI

cmd/run.go, internal/run/target.go, internal/run/testing.go, internal/run/workflow.go
Reference: https://linear.app/speakeasy/issue/GEN-779/feature-speakeasy-run-cli-command-support-for-target-testing
Reference: https://www.speakeasy.com/docs/workflow-file-reference#targets
If a workflow configuration (`.speakeasy/workflow.yaml`) target enables testing, e.g.
```yaml
targets:
TARGET:
testing:
enabled: true
```
Then the `speakeasy run` command will now run target testing unless explicitly disabled with the `--skip-testing` flag. Verified the following:
* No/disabled `targets.TARGET.testing.enabled` does not show or run target testing steps
* Test success generates output like the following:
```
│ Workflow - success
│ └─Target: petstore-sdk - success
│   └─Source: sample-source - success
...
│   └─Validating gen.yaml - success
│   └─Generating Go SDK - success
...
│ …
```
=> feat: Enable testing in workflows via speakeasy run

cmd/status.go
Previously would return (legit / errant):
```
Account Type: free (Business Trial Expires: 5 days 2 hours)
Account Type: business (Business Trial Expired)
```
Now will see (legit / corrected):
```
Account Type: free (Business Trial Expires: 5 days 2 hours)
Account Type: business
```
=> fix: Prevent errant trial expiry in status command

go.mod, go.sum
Reference: https://github.com/speakeasy-api/speakeasy-core/pull/103
=> fix: Prevent extraneous newline after hostname in generated API Key names

cmd/lint/lint.go
Reference: https://github.com/speakeasy-api/speakeasy/pull/1154
The referenced `speakeasy api` set of commands were previously removed.
=> chore: Remove outdated lint command output about api command

cmd/run.go, internal/run/run.go, internal/validation/openapi.go
Fixes two issues:
- Before, we would panic when given a ruleset that's missing from `lint.yaml`. We now check earlier for the ruleset and return a nicer error
- There was a longstanding visual issue with `run` output where we would double print every error. This fixes that
=> chore: validate custom linting rulesets sooner

cmd/openapi/transform.go, integration/resources/normalize-input.yaml, integration/resources/normalize-output.yaml, internal/transform/normalize.go, internal/transform/normalize_test.go
This pull request introduces a new feature to normalize OpenAPI documents to a more supported structure. The main changes include adding a new command for normalization, implementing the normalization logic, and adding tests to ensure the feature works correctly.
New normalization command:
* [`cmd/openapi/transform.go`](diffhunk://#diff-f618debf6dbd5b8b72bdb3a3772aff1757bd578d0810643b6821fb87c7c6f864L17-R17): Added `normalizeCmd` to the list of commands and defined its usage, flags, and run function. [[1]](diffhunk://#diff-f618debf6dbd5b8b72bdb3a3772aff1757bd578d0810643b6821fb87c7c6f864L17-R17) [[2]](diffhunk://#diff-f618debf6dbd5b8b72bdb3a3772aff1757bd578d0810643b6821fb87c7c6f864R100-R130)
Normalization logic implementation:
* [`internal/transform/normalize.go`](diffhunk://#diff-4887fac2f …
=> feat: added normalize transform

go.mod, go.sum
This pull request includes a minor update to the `go.mod` file to bump the version of the `sdk-gen-config` dependency.
Dependency update:
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L28-R28): Updated `github.com/speakeasy-api/sdk-gen-config` from version `v1.29.1` to `v1.29.2`.
=> fix: bump sdk-gen-config for updated workflow transform validation

go.mod, go.sum
This pull request includes a minor update to the `go.mod` file. The change involves updating the version of the `sdk-gen-config` dependency.
Dependency update:
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L28-R28): Updated `github.com/speakeasy-api/sdk-gen-config` dependency from version `v1.29.1` to `v1.29.3`.
=> fix: bump sdk-gen-config

.github/workflows/documentation.yml
Reference: https://github.com/speakeasy-api/speakeasy-registry/tree/main/web/packages/marketing-site/src/pages/docs/speakeasy-reference/cli
The documentation directory was moved, which broke this automation.
```
Run go run cmd/docs/main.go -out-dir ../speakeasy-registry/web/packages/marketing-site/src/pages/docs/speakeasy-cli -doc-site
2025/01/03 16:04:06 open ../speakeasy-registry/web/packages/marketing-site/src/pages/docs/speakeasy-cli: no such file or directory
exit status 1
```
This change updates the website documentation directory and sets up notifications to the #docs Slack channel on failures.
=> chore: Fix documentation website update automation and add Slack notifications

cmd/docs/main.go, internal/docs/docs.go
Reference: https://github.com/speakeasy-api/speakeasy-registry/pull/3360
The current script would make now-unexpected changes to the website given upstream changes. Verified these updates by running locally with the same command given to the website PR generation and reviewing the difference.
=> chore: Update documentation generation for website changes

.github/workflows/validate.yml, cmd/billing.go, cmd/root.go
This PR adds a new CLI command `speakeasy billing activate-webhooks` activate the webhooks feature and confirm to the user it will be paid.
[Context](https://speakeasyapi.slack.com/archives/C05G299KHQR/p1736192700464449?thread_ts=1736189281.484219&cid=C05G299KHQR)
https://github.com/user-attachments/assets/217a8b68-a520-4990-912f-37e8bcbc25ec
=> feat: add billing activate-webhooks command

cmd/billing.go, go.mod, go.sum
- prevent map examples from retaining obsolete key-value pairs (#2089) (commit by @2ynn)
- python: add missing import for per-operation servers (#2090) (commit by @disintegrator)
- typescript: webhooks security parsing of consumer should provide secret (#2088) (commit by @mfbx9da4)
- expose sdk versioning data as constants in python (#2077) (commit by @walker-tx)
- feature flag based licensing (#2078) (commit by @mfbx9da4)
- Upgrade to poetry 2.0 in pythonv2 (#2074) (commit by @bflad)
- Bump pythonv2 minimum version to 3.9 as 3.8 is no longer supported (#2072) (commit by @bflad)
=> feat: bump generator: Python upgrades, bug fixes, and feature flags

prompts/sources.go
https://linear.app/speakeasy/issue/SPE-4583/bug-quickstart-doesnt-throw-a-reasonable-error-when-given-oas-file
This is very low risk IMO
=> fix: check if file exists before asking for auth

go.mod, go.sum
- Handle 4XX and 5XX error ranges separately to ensure proper response ordering and avoid unreachable code paths. 
- Escape template-sensitive characters in examples across all targets to prevent templating errors in usage snippets.
- Add `enableCustomCodeRegions` configuration option to Pythonv2 SDK.
=> fix: improve error handling, templating, and Python config options 

prompts/github.go
The username is required param for the packagist API
=> fix: add missing packagist username secret

go.mod, go.sum
Setting upper bounds on dependencies is strongly discouraged for packages in the python ecosystem:
- https://discuss.python.org/t/should-i-be-pinning-my-dependencies/13159/2
- https://iscinumpy.dev/post/bound-version-constraints/
- https://hynek.me/articles/semver-will-not-save-you/
- https://github.com/python-poetry/poetry/issues/3747
=> fix: unpin python dependencies

internal/model/command.go, internal/updates/updates.go
If `run` completes successfully using `latest`, promote the used version to be the installed CLI version (as if the user had run `speakeasy update`)
Also cleans up some of the logging to be a bit less obnoxious
https://linear.app/speakeasy/issue/SPE-4408/speakeasy-run-too-many-version-update-mentions
=> feat: promote speakeasy version on successful run

internal/run/sourceTracking.go
Also fixes speakeasy's internal regression tests, once the next generation happens, for any affected repos. Will require 1 generation to fix bad data in workflow.lock first.
=> chore: fix change detection when there is a single registry source as an input

go.mod, go.sum
Stops pushing createdAt as part of registry annotations
=> chore: bump -core version

prompts/github.go
If there is already a matching package manager config, then don't overwrite it when running `speakeasy configure targets`
=> fix: skip predefined publish config sections when running `speakeasy configure targets`

.github/workflows/validate.yml, .golangci.yml
This specifically is being added to enable `go vet` static analysis reports, as `go test | gotestfmt` build errors caused by `go vet` issues are an opaque panic. Other linters can and should be enabled over time.
Verified by introducing a Go 1.24 errant change and noting that both `go vet ./...` and `golangci-lint run ./...` with this configuration both report the same error:
```console
$ go vet ./...
cmd/generate/generate.go:254:17: non-constant format string in call to (github.com/speakeasy-api/speakeasy/internal/log.Logger).Printf
$ golangci-lint run ./...
cmd/generate/generate.go:254:17: printf: non-constant format string in call to (github.com/speakeasy-api/speakeasy/internal/log.Logger).Printf (govet)
logger.Printf(changeLog)
^
```
=> chore: Enable golangci-lint in CI for go vet reports

internal/run/workflow.go
Certain targets like go actually need compilation to have run for `speakeasy test` to work. I also generally changed my mind and don't think it's bad to compile here.
=> feat: boostrapping tests should compile

go.mod, go.sum
This change adds a new feature to TypeScript SDKs to generate a Model Context Protocol server that is published with every SDK. The server hosts every standalone function as callable tool and can be run over STDIO or an SSE server.
=> feat: generate model context protocol servers

internal/usagegen/usagegen.go, pkg/codesamples/codesamples.go
The lib wasn't correctly parsing out snake case operation IDs causing downstream issues
Also we weren't handling single operations vs multi operation requests correctly
=> feat: fix usage snippet lib parsing snake care operation IDs

go.mod, go.sum
Correctly use artifactId as the sources jar name in `build.gradle`
=> fix: java publishing sources jar name

internal/studio/studioHelpers.go, internal/validation/openapi.go
The studio currently displays:
-  ValidationErrors – Generated from rule evaluations and explicitly added errors.
- Explicitly added Diagnostics – generally suggestions
Both are transformed into a type (confusingly named Diagnostic) that includes key details like the message, line number, schema path, severity, and type. These diagnostics are then rendered in the studio.
However, a category of validation issues visible in the CLI but missing from the studio are those logged via logging.LogWarning. This change ensures these warnings are also surfaced in the studio, providing a more consistent experience.
https://github.com/user-attachments/assets/bd1cc8f7-2441-4a7f-bcc8-270c93006abf
=> feat: plumb validation warnings into studio

go.mod, go.sum
GEN-1280
This release ensures the ClientCredentials hook is enabled even when no scopes are specified
=> fix: enable OAuth2 ClientCredentials hook when no scopes specified

go.mod, go.sum, main.go
introduces code to limit the GOMAXPROCS to the CPU Quota available to any running container and the GOMEMLIMIT to the memory available to any running container
Generally won't have an impact in local enviornments and should only impact builds running in github runners etc
=> chore: automatically set GOMAXPROCS and GOMEMLIMIT

cmd/quickstart.go
Makes it so that the CLI always presents the user with a Yes/No prompt asking them whether they'd like to launch the studio.
Selecting 'Yes' will launch the studio, whereas selecting 'No' will launch the Overview page in the webapp.
=> fix: always show confirm prompt for launching studio

cmd/quickstart.go
Previously, there was mixed up logic for how to handle Terraform target directory naming during the quickstart command.
Now its auto-populated correctly:
=> fix: Ensure terraform quickstart names directory terraform-provider-* by default

cmd/quickstart.go, go.mod, go.sum, prompts/configs.go, prompts/sources.go, prompts/statemappings.go
Adds support to the quickstart command to automatically fill the settings values for `sdkClassName` and `packageName` from a session in the Speakeasy Sandbox (sandbox.speakeasy.com)
https://github.com/user-attachments/assets/14a47594-d8e4-4ecf-affb-ea833ffdd7a4
=> feat: support autofilling of sdkClassName and packageName 

cmd/merge.go, cmd/migrate.go, pkg/merge/merge.go, pkg/merge/merge_test.go
- created `resolve` and `basePath` arguments to the merge command
- created a new function called `MergeByResolvingLocalReferences` in `pkg/merge`
- toggle off of `resolve` to use `MergeByResolvingLocalReferences` or the current `MergeOpenAPIDocuments`  
This PR adds support for resolving local references during OpenAPI merges by leveraging [pb33f's libopenapi bundler](https://pb33f.io/libopenapi/bundling/).
Instead of modifying the existing merge behavior—which simply combines multiple OAS documents without resolving references—I’ve introduced a new `--resolve flag` and `--basePath` argument to the merge command:
--resolve: triggers reference resolution using the first file as the base document
--basePath: defines the directory to begin resolving references from
This keeps the current …
=> feat: added a resolve flag and resolve by local references using libopenapi bundler

.gitignore, .goreleaser.yaml, scripts/completions.sh
I noticed that when installing `speakeasy` via the recommended method (`brew install speakeasy-api/homebrew-tap/speakeasy`) that
I didn't get completions setup for me like I normally would with homebrew installed commands.
I followed basically what the goreleaser folks themselves do (see [this commit](https://github.com/goreleaser/goreleaser/commit/fafeb9b0dc91c75bb1992d5578492eb1078636be)), but other packages do something very similar (see [go-task's goreleaser.yml](https://github.com/go-task/task/blob/6cb0a5a2f2d5db23a2a882d3c9aa5f1fea37106a/.goreleaser.yml#L90-L92)).
Once this lands (assuming one of y'all are able to test it out locally), it will enable shell completion automatically for homebrew users. 🎉 
---
Note, I cannot test this locally (it's not possible to run `go mod download` …
=> feat(release): add automatic shell completion support for homebrew

.goreleaser.yaml, scripts/completions.go, scripts/completions.sh
The GitHub action that does the release actually runs on Windows (likely makes publishing to Choco easier?). The changes to add completions for Homebrew caused errors during release because I had assumed a *nix like runtime environment for the GHA `release` job (incorrectly).
This replaces the shell script with a tiny go script that is platform agnostic.
---
Note: like the other changes, I am unable to test this myself (due to a private repo being referenced in `go.mod`). In order to test the new script, you should be able to run `go run scripts/generate.go` (which is what is done in the `.goreleaser.yaml` file).
=> fix(release): fix completion generation on windows

.goreleaser.yaml, scripts/completions.go, scripts/completions.sh
The GitHub action that does the release actually runs on Windows (likely makes publishing to Choco easier?). The changes to add completions for Homebrew caused errors during release because I had assumed a *nix like runtime environment for the GHA `release` job (incorrectly).
This replaces the shell script with a tiny go script that is platform agnostic.
---
Note: like the other changes, I am unable to test this myself (due to a private repo being referenced in `go.mod`). In order to test the new script, you should be able to run `go run scripts/generate.go` (which is what is done in the `.goreleaser.yaml` file).
=> fix(release): fix completion generation on windows (#1391)

internal/locks/locks.go, internal/locks/locks_test.go
Specify it within the update-scoped lock instead
Also, use a generic name for the mutex.
=> fix: do not specify default lock name

cmd/generate/generate.go, cmd/generate/sdk.go, cmd/generate/supportedTargets.go, integration/utils.go, internal/migrate/migrate.go, prompts/configs.go, prompts/github.go
This set of changes ensures that for the `configure publishing` command, the mcp-typescript target works similar to the typescript target. It also ensures that new target name is returned from the hidden `generate supported-targets` command, which is a requirement for sdk-generation-action to support the new target name.
=> fix: Ensure mcp-typescript support for configure publishing and sdk-generation-action

install.sh
When ran from a GitHub Actions workflow like:
```yaml
- name: Install Speakeasy CLI
run: curl -fsSL https://go.speakeasy.com/cli-install.sh | sh
```
You would very very often run into an issue with rate limiting (causing your actions workflow to fail). This is because, by default, the rate limit for requests to api.github.com is 60 requests per hour per originating IP address. In a GHA runner context you end up using shared IP address pools, and hit rate limiting issues pretty often.
This change updates the install script to use an authenticated request if the environment has `$GITHUB_TOKEN` available, if not it does what it's always done (uses an unauthenticated request). Authenticated requests have much higher rate limits. In a GHA scenario it's 1000 per hour per repo (with a PAT it is …
=> fix: Ensure install.sh script uses authenticated GitHub API calls (#1448)

cmd/configure.go
Implementation wise, `--rebuild` takes a single string. If it's value is `*` (the default) all tests are rebuilt, but you can specify a list of operationIds to clear only specific ones. The way you do that is by passing a single comma separated list of operationIds like `--rebuild listFoo,deleteBar` etc. 
It was unclear from the docs just how to specify multiple entries, so I added a bit more prose to the help output. I'm happy to tweak / iterate on the prose if y'all have suggestions.
---
Note: CI will not pass due to being from a fork (forks don't get access to secrets which are needed to setup CI for testing).
=> docs(configure): Passing multiple value to `tests --rebuild`

prompts/sources.go
It's nice to have the resulting spec checked into the repo (under the .speakeasy folder) for debugging and reviewing PRs more easily.
=> feat: set default output for sources

go.mod, go.sum
- fixed NullPointerException being raised at Utils.getHeadersFromMetadata (Java), 
- add debug logging convenience methods to SDK builder and HTTP client (Java), and 
- fix issue using int examples in double fields (Java), and 
- various improvements to the standalone typescript mcp server
=> fix: various java fixes, and mcp-typescript updates

go.mod, go.sum
• Upgraded openapi-generation dependency from v2.638.5 to v2.639.2
• Fix: prevent erroneous mock server generation for SDKs without tests
• Fix: java make debug logging flag accessible from sdkconfiguration
=> fix: mock server generation for SDKs without tests and expose Java SDK debug logging flag

go.mod, go.sum
feat: Add testproject for Ruby,
fix: missing title and description in main usage examples when using x-speakeasy-globals
=> feat: Add testproject for Ruby, fix missing title and description in main usage examples when using x-speakeasy-globals

go.mod, go.sum
Enables support for deploying Speakeasy's generated MCP server to Cloudflare, in addition to other stability fixes.
=> feat: Cloudflare MCP deployment support & stability fixes

prompts/utils.go
Get rid of the bundled TS-MCP option under MCP target since we no longer generate an MCP server alongside the TS target automatically.
Fixed:
=> fix: remove TS as an MCP target

internal/run/source.go
Presumably, the validation step was previously marked as successful to indicate the execution of the step itself was successful. Even so, this is confusing for users - we now mark it as failed if we identify a validation error.
**Unhappy Path**:
**Happy Path**:
=> fix: mark validation step as failed if there are lint errors

internal/run/target.go
These logs make it easy to understand from the sdk-action what happened when speakeasy cli generated sdks
=> chore: Add logs specific to new changelog feature which helps in debugging 

cmd/run.go, internal/run/dependent.go, internal/run/run.go, internal/run/source.go, internal/run/workflow.go
Adds a flag source-location that gives the option to override the source location for a single SDK run
Uses this new flag to power `dependents` in a cleaner way
=> feat: source-location flag for speakeasy run

internal/model/command.go
This was missed because it only happens outside of local development (e.g. after releasing the CLI)
=> fix: don't write local overrides to real workflow

cmd/tag.go
Reference: https://linear.app/speakeasy/issue/GEN-1956/bug-cli-segmentation-fault-in-speakeasy-tag-promote-command
=> fix: Ensure tag promote command returns workflow.lock error
