speakeasy-api/speakeasy

.gitignore, go.mod, go.sum
=> fix: use qualified python imports

README.md
Include options to use a local env var for Speakeasy platform API keys.
=> Update docs with auth and other minor updates

cmd/suggest.go, cmd/validate.go, internal/suggestions/utils.go, internal/validation/openapi.go
Sets up the ability to auto continue through props during suggestions. This is a must have for the github action to use this CLI command.
Also settings this up for flexibility because I figure I will need to add some more configuration options such as max number of suggestions and maybe parallelization.
=> feat: auto continue for suggestions

cmd/suggest.go, go.sum, internal/validation/openapi.go
Provide a max number of llm suggestions to fetch
=> feat: max suggestions to fetch

go.mod, go.sum, internal/auth/auth.go, internal/config/config.go
* Enables the speakeasy CLI to be tested against development, staging environments.
=> chore: respect SPEAKEASY_SERVER_URL variable

cmd/suggest.go, internal/suggestions/client.go, internal/suggestions/utils.go, internal/validation/openapi.go
add an optional argument for openai model
=> feat: argument for openai model

cmd/docs/main.go, internal/config/config.go, internal/docs/docs.go, internal/sdkgen/sdkgen.go, internal/updates/updates.go, internal/usage/usage.go, internal/utils/utils.go
Prefer non-world-readable/writable permissions.
=> fix: use 0755 for dirs and 0644 for files created

go.mod, go.sum
=> feat: add go mod tidy before go build

go.mod, go.sum, internal/suggestions/fileFormatter.go, internal/suggestions/suggestions.go, internal/validation/openapi.go
Also removes excess printing of warnings
=> feat: maintain key ordering in output when applying LLM suggestions

cmd/suggest.go, docs/suggest.md, internal/suggestions/client.go, internal/suggestions/suggest.go
Speakeasy will provide our own platform openai key. Providing your own key will now be an optional parameter
=> feat: openai key not required

internal/suggestions/client.go
Fixing a bad rebase in the prior PR
=> fix: OpenAI platform key

.github/workflows/documentation.yml
This should fix the documentation workflow failures.
=> chore: the documentation directory moved

go.sum, internal/suggestions/client.go, internal/suggestions/suggestions.go
Doesn't do anything, just adding some code that may be useful in the future
=> chore: support for preprocessing errors

go.mod, go.sum
- Also includes code for Go multi-level SDKs in between
=> fix: github action badge for sdks

internal/suggestions/suggest.go, internal/suggestions/suggestions.go
Basically if you look at the result of suggest on [certain specs](https://github.com/speakeasy-sdks/apiture-ts-sdk/pull/142), the line numbers for the PR comments are fairly shifted.
This should enable it to be more accurate because we actually don't want the line numbers to be updated after each suggestion is applied. We want to keep the old line numbers as this should create a better comment on the PR diff. Testing locally now
~~EDIT: Current implementation doesn't fix the issue, so will mark PR as draft for now until it's resolved~~
=> fix: inaccurate line numbers in suggest comments

go.mod, go.sum
=> feat: add support for nullable unions in Go

README.md, go.mod, go.sum
=> feat: throw warning on usage of anyOf and treat as oneOf

internal/suggestions/suggestions.go
=> fix: ensure that suggest handles new limits arg

go.mod, go.sum
Includes
- feat: make codespaces readme more clear
- fix: make python usage snippets valid
- feat: java generated gradle project should require at least JDK 11
- fix(python): add missing dateutil import
=> feat: oct 12 release

go.mod, go.sum
- feat: use override name in sdk docs
- add extra error messages to avoid invalid usage of x-speakeasy-entity annotations 
- fix: support both serverIDs and variables in TS 
- docs: custom http client- 
- docs: add error handling examples to readme
=> feat: 10-25 release

go.mod, go.sum
- sub sdk paths sdk docs 
- handle an edge case with no request body on an x-speakeasy-entity-operation operation
- remove fields from python keywords
=> feat: 10-27 release 2

cmd/overlay.go, go.mod, go.sum
* Also enables absolute references of overlay files passed via args.
=> chore: overlay file can now lack a schema

go.mod, go.sum
=> feat: pulumi support, robust name changes (shorter union names) applied to terraform

internal/download/download.go
Implements basic retries on 5xx for spec downloads
=> feat: implement retries for spec downloads

go.mod, go.sum
=> feat: async iterators in TS, improved ergonomics in terraform #390, const/defaults in TSv2

go.mod, go.sum, internal/sdkgen/sdkgen.go, quickstart/configs.go
=> feat: added support for preview of java v2 generated sdks plus various fixes

go.mod, go.sum
- remove excessive base64 helper import Typescript
- SSE Support for Go
- SDK Docs Paramter Styling Fix
- Java Download Streaming
=> chore: bump cli 1/18

go.mod, go.sum
=> feat: (terraform) push default values into Computed + Optional fields Schema. (javav2) support const primitives

.gitignore, internal/run/run.go, internal/utils/utils.go
=> feat: add timer success to speakeasy run

internal/charm/styles/styles.go, internal/run/run.go, internal/validation/openapi.go
Also improves successful `run` output
=> fix: improve validation success output

cmd/run.go, internal/run/run.go, internal/run/workflowMermaidVisualizer.go, internal/run/workflowTracking.go
Small change to print the mermaid summary from the correct place
=> feat: print mermaid to gh action summary

.github/workflows/validate.yml
Noticed today it's actually pretty easy to pull in a dependency that causes the CLI to not compile but nothing will prevent you from merging to main.
This just adds a basic compile check
=> feat: add compile check to CLI CI

cmd/quickstart.go, cmd/run.go, internal/interactivity/interactiveexec.go, internal/interactivity/listSelect.go, internal/model/command.go, internal/model/flag.go, internal/run/run.go, internal/utils/utils.go
Adds support for map flags
Used a map flag to add an installationURLs flag to `run`. This allows us to use it from the action
=> feat: mapFlags and installationURLs arg for run

cmd/run.go, internal/charm/styles/styles.go
- (finally) moves `run` target prompt to use charm
- (finally) fixes light mode theme (especially new version popup)
=> fix: interactive mode improvements

go.mod, go.sum
- fix: flattened security fieldname sanitization C#/Unity
- Implement retry-after header support in typescript
- Implement URL pagination in typescript.
=> feat: typescript url pagination and retry header support

cmd/migrate.go, cmd/run.go, internal/run/run.go
Issues found while testing some preliminary customers
=> fix: migrate and run improvements

cmd/configure.go, internal/charm/formModel.go, internal/charm/styles/styles.go, internal/interactivity/listSelect.go, internal/interactivity/tabs.go, internal/run/run.go, prompts/github.go
=> fix: make boxes more responsive on smaller terminals

cmd/configure.go, internal/charm/styles/styles.go, prompts/github.go
=> feat: provide github links in configure when available

cmd/configure.go, prompts/github.go
- Makes some fixes to the publishing action file
- Supports new publishing target configurations (PHP, Java)
=> feat: support additional publishing configurations

cmd/run.go, internal/run/workflowMermaidVisualizer.go
This change removes a panic from the mermaid visualization code that was causing workflow runs to fail when the generated graph was deeper than two levels.
We are now treating all mermaid errors as non-fatal and instead logging errors and printing an appropriate message to the user in the action summary.
=> fix: prevent mermaid errors from crashing workflow

cmd/configure.go, prompts/github.go
autoselect publishing targets in `speakeasy configure publishing`
=> feat: autoselect publishing targets

prompts/github.go
=> fix: clarify publishing config prompts

go.mod, go.sum, internal/charm/styles/styles.go, internal/sdkgen/sdkgen.go
Final CLI change to get blocking access checks ready.
The messaging will be different when I turn this on from the backend next week. But this is what the styling will look like
=> feat: access checks finalized

internal/run/run.go, internal/run/workflowMermaidVisualizer.go, pkg/merge/merge.go
Also contains an improvement to mermaid output
=> fix: don't print merge warnings

internal/charm/formModel.go, internal/charm/internalModel.go, internal/interactivity/listSelect.go, internal/interactivity/multiInput.go, internal/interactivity/simpleInput.go, internal/interactivity/tabs.go, internal/run/workflowCliVisualizer.go, internal/run/workflowTracking.go
=> fix: better workflow output on user exit

cmd/configure.go, cmd/quickstart.go, internal/run/run.go
=> feat: prompt speakeasy run from configure/quickstart

cmd/ask.go, cmd/root.go, internal/interactivity/listSelect.go, internal/model/command.go
=> chore: adjust ask for interactive mode

internal/validation/customConfigValidators.go
The generator panics if one of them is missing
=> fix: better additionalDeps python validation

cmd/quickstart.go, internal/charm/utils.go
=> feat: remove secondary title for quickstart

cmd/lint.go, cmd/run.go, go.mod, go.sum, internal/api/schemas.go, internal/run/run.go, internal/suggestions/example_experiment.go, internal/suggestions/suggestions.go, internal/validation/openapi.go, pkg/merge/merge.go
- Adds the uploading of the linting-report to the platform if possible otherwise creates it locally
- Adds output to speakeasy run of where to find the report
=> feat: add support for uploading report to dashboard

internal/updates/updates.go
This logic is behind a feature flag
=> fix: write to temp dir in GH actions

internal/model/command.go
=> fix: continue running if version is the same

internal/run/run.go
=> fix: move linting report out of box

internal/validation/openapi.go
This will facilitate display links to the linting reports from the OpenAPI source and vice versa
=> feat: append lint report data to CLI events

cmd/openapi.go, internal/run/run.go, registry/utils.go
Integrates pulling speakeasy registry bundles into `speakeasy openapi diff`
=> feat: integrate registry bundles into diff

internal/run/run.go
I have a more elegant fix for this coming in a different PR, so just putting the quick and dirty thing up now
=> fix: nil checks in source message

internal/charm/styles/styles.go
=> chore: darken adaptive light mode yellow

internal/run/run.go
- only automatically tag on github environment runs
- add a branch tag automatically to each registry push
=> feat: implicit registry tagging

cmd/configure.go, prompts/github.go
Github actions doesn't not support nested .github/workflows structure
=> fix: monorepo configure setup

go.mod, go.sum
Fix: nested namespaces in usage snippets
Feat: reduce response handling boilerplate in TS
Fix: pointer request objects in go
Feat: Java dev containers
=> chore: cli deploy 5/22

go.mod, go.sum
- generic filename examples 
- fixes typescript error output
=> chore: 5 24 cli deploy

cmd/generate/codesamples.go, go.mod, go.sum, internal/run/run.go, internal/usagegen/codesamples.go
=> feat: push code samples to registry

go.mod, go.sum, internal/run/run.go
Will fix linting report background color release
=> chore: bump openapi generation 

cmd/tag.go, go.mod, go.sum, internal/api/eventlog.go, internal/api/register.go, internal/model/command.go, internal/utils/utils.go
Reverts speakeasy-api/speakeasy#740
=> Revert "feat: add speakeasy tag promote command"

cmd/tag.go, internal/run/run.go
Also improves `tag promote` functionality when info is missing from `workflow.lock`
=> feat: persist codesamples revision info to workflow.lock

internal/run/run.go, internal/utils/utils.go, internal/validation/openapi.go
Removes the following for zero metadata customers
- Uploaded Change Report
- Uploaded Linting Report
- Redirect to webapp SDK entry in quickstart
=> feat: handle zero metadata customers

internal/validation/config.go
for some reason pythonv2 is not showing up in target.Template. This will do for now
=> feat: check python template version in config validation

cmd/configure.go, prompts/configs.go
Default dev containers to on for new go, python, and typescript SDKs
=> feat: default on dev containers

internal/run/source.go
We shouldn't block the whole generation workflow for snapshot source, same as what we are doing with openapi changes
=> feat: dont block generation snapshot source

cmd/clean.go, cmd/root.go, internal/interactivity/hiddenCommands.go
easy dx request we got for a command to clean up stale entries in .speakeasy folders.
https://linear.app/speakeasy/issue/SPE-3489/feature-need-means-of-cleaning-up-old-speakeasy-cli-binaries-and
=> feat: speakeasy clean command

prompts/github.go
Verified locally via:
```console
❯ ~/go/bin/speakeasy configure publishing
A new version of the Speakeasy CLI is available: v1.326.0
Run `speakeasy update` to update to the latest version
Files successfully generated!
• Speakeasy workflow written to - /Users/bflad/test/my-first-target/.speakeasy/workflow.yaml
• GitHub action (generate) written to:
•     - /Users/bflad/test/my-first-target/.github/workflows/sdk_generation.yaml
• GitHub action (publish) written to:
•     - /Users/bflad/test/my-first-target/.github/workflows/tf_provider_release.yaml
•     - /Users/bflad/test/my-first-target/.goreleaser.yml
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ For your publishing setup to be complete perform the following steps. …
```
=> fix(configure): Ensure GoReleaser configuration contents are correct

go.mod, go.sum, prompts/configs.go, prompts/sources.go
https://speakeasyapi.slack.com/archives/C0698C9K4NL/p1721327668366689
=> feat: dynamic quickstart descriptions

cmd/status.go
Reuses the web application logic.
=> fix: Skip archived targets more accurately with status command

go.mod, go.sum
* We now generate standalone functions in TypeScript (experimental feature)
* Fixed python linting errors
* Fix documentation examples in Terraform
=> feat: new TS features and bug fixes in terraform and python

go.mod, go.sum
=> feat: add support for URL-encoded forms in undiscriminated unions C#

cmd/generate/sdk.go, internal/model/flag/enumFlag.go
https://speakeasyapi.slack.com/archives/C0698C9K4NL/p1723065024751839
=> fix: make lang flag required

cmd/generate/sdk.go, internal/model/flag/enumFlag.go
This reverts commit d969459ad12dc18decb6a84ba061d953a6ff9a90.
=> Revert "fix: make lang flag required (#843)"

go.mod, go.sum
* **Our TypeScript v1 and Java v1 code generation targets have been removed. The v2 targets now replace them.**
* Fixed infinite recursion bugs when generating usage snippets
* Added README note to Python SDKs about PyCharm plugin for Pydantic
* Fixed syntax error related to additionalProperties handling in TypeScript
=> fix: removed sunset targets and fixed bugs in TS and Python

cmd/generate/sdk.go, internal/model/flag/enumFlag.go
Reverts speakeasy-api/speakeasy#844
=> chore: Revert "Revert "fix: make lang flag required (#843)""

go.mod, go.sum, internal/run/workflow.go, internal/studio/launchStudio.go, internal/studio/studioHandlers.go
=> fix: studio improvements

internal/run/remote.go
https://linear.app/speakeasy/issue/SPE-4013/speakeasy-run-remote-gh-action-link
=> feat: wait for the correct run url in github run remote

cmd/configure.go, cmd/quickstart.go, internal/charm/styles/styles.go
=> feat: clarify directory output instructions

internal/download/download.go
* In the case where a single schema registry entry was used to generate an SDK, we fixed an issue where we didn't previously compute a change report for the SDK, and ensured the schema registry blob was deterministic.
* However upon generating a changereport for the case where the prior OAS is the same as the current OAS, we now produced an error as the CLI attempted to download the prior revision and the current revision into the same place (because the hash of the blob was the same).
* This produced an error because we'd set a read-only file permission into our bundle. 
Changes here are:
1. If the file content is the same when we're extracting a zip, we don't try and override the file. 
2. If the file content is different (e.g. a SIGKILL happened during zip extraction), we delete the …
=> chore: hotfix issue with speakeasy run

cmd/overlay.go
The overlay command currently takes in a comma separated list of schemas but it doesn’t dictate the order of specs. To improve, changing this to before and after inputs.
https://www.speakeasy.com/docs/speakeasy-cli/overlay/compare
=> feat: Use before and after inputs for overlay command

go.mod, go.sum
=> fix: improve support for const fields with defaults in TypeScript

internal/charm/utils.go, prompts/sources.go
- Improves file path suggestions in the Quickstart command
https://github.com/user-attachments/assets/7608e051-cc04-494d-a7c8-03d811ffb295
- Adds validation for file path existence + URI validity
https://github.com/user-attachments/assets/75f4e98c-dde4-4817-ae64-b7e2bc9aad0c
=> feat: improve path completions and add file + uri validation to Quickstart command

go.mod, integration/workflow_registry_test.go, integration/workflow_test.go, internal/run/source.go, internal/run/workflow.go, internal/studio/launchStudio.go, internal/studio/modifications/overlay.go, internal/studio/oas_studio.yaml, internal/studio/sdk/.speakeasy/gen.lock, internal/studio/sdk/.speakeasy/gen.yaml, internal/studio/sdk/.speakeasy/speakeasy-modifications-overlay.yaml, internal/studio/sdk/.speakeasy/workflow.lock, internal/studio/sdk/docs/sdks/sdk/README.md, internal/studio/sdk/internal/utils/requestbody.go, internal/studio/sdk/sdk.go, internal/studio/studioHandlers.go
* Fixes formatting issue of overlay (using wrong version of yaml - also uninstall v2 as doesn't seem to be used)
* Re-enables supporting multiple studio modification overlays
=> feat: studio overlay fixes

internal/charm/utils.go
This PR reinstates completions for the cwd to the previous state. For more complex completions (nested relative paths to the current wd for example), I will create a follow up pr.
=> fix: reinstate completions for cwd

internal/studio/studioHandlers.go
We want the overlay path to be shown as an absolute path
=> feat: make overlay path absolute

internal/run/minimumViableSpec.go, internal/run/workflow.go, internal/studio/modifications/overlay.go, internal/studio/studioHandlers.go
Quick one to share overlay path logic between MVS and suggest
=> fix: make sure MVS and suggest use same overlay path

cmd/quickstart.go, internal/studio/studioHandlers.go
=> feat: release studio!

cmd/quickstart.go, internal/interactivity/button.go
=> chore: add helper text to launch studio button

internal/studio/studioHandlers.go
Call `filepath.Rel` on relative paths which in turn calls `filepath.Clean` in order to produce the shortest version of the relative path possible.
=> fix: clean relative paths for workflow inputs

go.mod, go.sum, internal/run/target.go
Related `sdk-gen-config` pr will come
=> chore: don't write outLocation to workflow.lock

.vscode/launch.template.json, cmd/quickstart.go, cmd/run.go, internal/log/log.go, internal/run/target.go, internal/studio/launchStudio.go
Also fixes some other CLI output styling issues
=> fix: don't prompt about studio after run

internal/usagegen/usagegen.go
Make sure usage snippets are parsed out of content in a stable manner.
=> chore: one more form of lack of codesamples stability

go.mod, go.sum, internal/sdkgen/sdkgen.go
Waiting on https://github.com/speakeasy-api/openapi-generation/pull/1709
=> feat: readme improvements

cmd/quickstart.go, go.mod, go.sum
Needs: https://github.com/speakeasy-api/speakeasy-core/pull/88
=> fix: flush cli event before launching studio

internal/transform/cleanup.go, internal/transform/filterOperations_test.go, internal/transform/transformer.go
Bug introduced last week. Added a test to catch it next time
=> fix: properly remove unused paths once again

prompts/sources.go
Fixes a small bug whereby `speakeasy configure` would accept an empty string for the OAS location prompt value 
- https://app.usepylon.com/issues?conversationID=0653984f-5f12-4f30-b5be-9fa03cc81dd1&messageID=b417774c-e655-45b6-b4a4-e2817788c7f0
=> fix: fix configure accepting empty oas location

cmd/configure.go, internal/arazzo/arazzo.go, internal/charm/styles/styles.go, internal/sdkgen/sdkgen.go, prompts/github.go
Support speakeasy workflow file not in root of repo via flag
=> feat: speakeasy configure nested workflow directory by flag

cmd/configure.go, go.mod, go.sum, prompts/github.go
Updates publishing workflow file generation in speakeasy configure publishing to include
- New trigger from gen.lock
- Workflow dispatch functionality
=> feat: update publishing workflow file generation

cmd/run.go
Adds a `--minimal` flag to `run` in the CLI, which skips all the superfluous stuff (change report, lint report, and snapshotting)
=> feat: add minimal flag to run

go.mod, go.sum
Actual change [here](https://github.com/speakeasy-api/speakeasy-core/commit/09fce7ee1b5678acca0ea7396cb950d83747dce5)
=> feat: update access checks

cmd/configure.go
https://linear.app/speakeasy/issue/SPE-4365/feat-add-create-pull-request-permissions-to-configure-github-step
=> feat: workflow permission reminder

go.mod, internal/run/frozenSource.go, internal/run/merge.go, internal/run/overlay.go, internal/run/source.go, internal/run/sourceTracking.go
Should be no functional change, just a code cleanup
=> chore: cleanup run code

internal/run/source.go
@simplesagar lmk what copy you would like
=> feat: cleaner lib openapi error message

.github/workflows/validate.yml, go.mod, go.sum, integration/resources/renameOperationOverlay.yaml, integration/workflow_test.go, internal/run/frozenSource.go, internal/run/merge.go, internal/run/minimumViableSpec.go, internal/run/overlay.go, internal/run/source.go, internal/run/transform.go, internal/transform/cleanup.go, internal/transform/filterOperations.go, internal/transform/removeUnused.go, internal/transform/transformer.go
Adds support for `transformations` during run.
=> feat: transformations support in run

internal/run/minimumViableSpec.go, internal/run/transform.go, prompts/sources.go
Some slight fixes
[GEN-743](https://linear.app/speakeasy/issue/GEN-743/operations-not-showing-up-in-generated-sdk-copy)
=> fix: fix MVS with transforms 

go.mod, go.sum
https://speakeasyapi.slack.com/archives/C07VB6BFSG3
=> fix: codeSamples backfill edge case

cmd/quickstart.go
=> chore: print a nice message when things removed by quickstart

go.mod, go.sum
=> feat: java additionalProperties, customizing default error name; revert x-speakeasy-terraform-alias-to, improve markdown tables in readme

go.mod, go.sum
https://speakeasyapi.slack.com/archives/C05JZT0RADP/p1731365959022779
=> fix: ignore unneeded check on error codes type

internal/run/sourceTracking.go
Pairs with [sdk-generation-action](https://github.com/speakeasy-api/sdk-generation-action/pull/188)
=> feat: active branch tagging

prompts/sources.go
* Derives the OAS name inside the workflow.yaml based on the OpenAPI Info.Title attribute
=> chore: oas names from document info

go.mod, go.sum
* go: Prevent test client import error
* mockserver: Prevent missing `testfiles` directory error
=> fix: Various fixes for test generation

internal/run/sourceTracking.go, internal/run/target.go
https://speakeasyapi.slack.com/archives/C0698C9K4NL/p1733423158679549
=> fix: dont set reproducible on registry push

prompts/targets.go, prompts/utils.go
=> chore: block alpha languages in quickstart

cmd/generate/generate.go, internal/interactivity/hiddenCommands.go, internal/interactivity/interactiveexec.go, internal/model/command.go
=> chore: hide generate from help output and generated docs

go.mod, go.sum
- We now respect the defaults for pagination inputs if they are set in an OpenAPI document. This prevents instances where the first page of results is double-fetched in Python, Go and TypeScript.
- TypeScript now targets ES2020
- Updated Apache HTTPClient in Java
- Add null check for non-optional required security in C#
- Fixes usage snippets in C#
=> feat: support for retries in PHP, support for custom webhook security in TS and several bug fixes

go.mod, go.sum
releasing this fix
https://github.com/speakeasy-api/speakeasy-core/pull/104
=> chore: bump speakeasy core

README.md
Update language count copy and add links to swift and unity documentation
=> chore: Add swift and unity logos

go.mod, go.sum
bump sdk gen config code sample default labels
https://github.com/speakeasy-api/sdk-gen-config/pull/71
=> feat: bump sdk gen config code sample default labels

cmd/quickstart.go
Currently we do not prompt the user before running `git init` at the end of `speakeasy quickstart`, but we should.
This PR adds a new branch prompt to ensure that the user can choose
=> fix: prompt user to determine if git repo should be init-ed

go.mod, go.sum, pkg/merge/merge.go, pkg/merge/merge_test.go
Most of the changed behavior is actually coming from[ this sdk-gen-config change](https://github.com/speakeasy-api/sdk-gen-config/pull/74)
=> feat: pass through json documents during source compilation

cmd/quickstart.go
Quick follow up to https://github.com/speakeasy-api/speakeasy/pull/1194
I hoisted the prompt up top before run as that's where all the other questions go
=> fix: git init prompt

.gitignore, go.mod, go.sum
- if a readme section lacked a TOC, the readme could get deleted on a subsequent regeneration (#2102) (commit by @ThomasRooney)
- moved pylint disable comment (#2099) (commit by @walker-tx)
- add support for custom code regions in TS/Py (#2073) (commit by @disintegrator)
=> fix: upgrade generator: readme fix, custom code regions

go.mod, go.sum
-  Added support for unions of arrays in PHP
- Introduced capability for operations to map exclusively to a data source or resource
- Fixed stale filepath reference in readme
- Updated Python EOL policy
- Updated snapshot test guide for better clarity - Bumped `testbench-orchestra` version to address security
=> feat: enhance array union handling and operation mapping; various fixes and improvements

cmd/testcmd.go, go.mod, go.sum
also fixes https://linear.app/speakeasy/issue/TESTGEN-20/ux-speakeasy-test-doesnt-ask-which-target-to-run-testing-against
=> fix: ask for which target to test if multiple targets present in workflow and includes various fixes for testing in general

go.mod, go.sum, internal/run/testing.go, internal/testcmd/runner.go, internal/testcmd/testing.go
- Starts writing testing CLI events including, github metadata, generator metadata, and a raw test report read after testing
=> feat: start writing test cli events

cmd/configure.go, internal/run/run.go, internal/run/workflow.go, prompts/github.go
`speakeasy configure tests`
- Shorten links for better CLI window rendering
- Fix check for existing app install
- Setup default target in action config
- Clearer workflow boostrapping tests message
- Fix typo in command description
=> feat: speakeas configure tests improvements

go.mod, go.sum
- feat: improve name resolution for inline schemas
- fix: handle circular references in go usage snippets
- fix:  reorder code in standalone functions 
- feat: return custom APIPromise from TS functions
- fix: show hidden logs
- chore: bump to go 1.24
=> feat: improved name resolution, return APIPromise from TS functions and more

cmd/billing.go, cmd/configure.go, go.mod, go.sum, internal/run/testing.go, internal/testcmd/runner.go, internal/testcmd/testing.go
Replaces existing testing check with billing add on functionality
Replaces existing webhooks feature add with billing add on functionality
=> feat: integrate billing add ons into the CLI

go.mod, go.sum
- feat: make nameResolutionFeb2025 the default for new SDKs
- terraform: Support map of array types
=> feat: make nameResolutionFeb2025 the default for new SDKs and Terraform now supports map of array types

README.md
Found a few grammar issues in the README.
=> docs:  Few small README tweaks

go.mod, go.sum
* nameResolutionFeb2025 tweaks: de-prioritize const discriminators & singularize array.item
=> feat: bump generator: nameResolutionFeb2025 fixes

go.mod, go.sum, internal/studio/studioHelpers.go
Blocked on: https://github.com/speakeasy-api/openapi-generation/pull/2430
=> chore: display skipped entities in diagnostics

go.mod, go.sum
- implemented ClientCredentials at the operation level for C#, PHP, JavaV2
- handled name conflict with operation security and  flattened request paramters
=> feat: implement op-level ClientCredentials C#, PHP, Java

prompts/github.go
adding java to supported testings targets
=> feat: adding java to supported testing targets

go.mod, go.sum
Fixes an issue whereby internal error logs would leak into the terminal output.
=> fix: error logs leaking into CLI output

go.mod, go.sum, internal/validation/openapi.go
Related to PR - https://github.com/speakeasy-api/openapi-generation/pull/2479
Updated the title to include all changes since generator version 2.565.0 ([link](https://github.com/speakeasy-api/openapi-generation/releases))
=> refactor: Refactor Code

go.mod, go.sum
=> feat: Ruby unions; TypescriptV2 operation-level security option OAuth2 Password flow fix; Java oauth2 expires_in units fix

go.mod, go.sum
- Add experimental request/response debug logging for Java SDK (GEN-1336)
- Fix Java cursor pagination with limit parameter (GEN-1339)
- Refactor Ruby error handling with proper ApiError class (GEN-1057)
=> fix: java cursor pagination, add java debug logging, and improve error handling in ruby.

cmd/generate/usage.go, go.mod, go.sum, internal/usagegen/usagegen.go
We expose a new filesystem interface from the generator which the usage snippet generator needs to adhere to
=> fix: upgrade generator, and update usage snippet cli arg description to reflect updated api

.github/workflows/release.yml
=> chore: add manual workflow dispatch

go.mod, go.sum
- ruby additional properties 
- add multi level support for ruby
- ruby const and default
- sharedErrorComponentsApr2025 fixes
=> feat: ruby additional properties, const, default and fixes to errors

go.mod, go.sum
* typescript: respect required status for const fields when constFieldsAlwaysOptional is false
* php unions fix
=> feat: typescript respect required-ness of const fields, php fix union deserialization

internal/run/source.go, prompts/sources.go
Reverts speakeasy-api/speakeasy#1471
=> chore: Revert "chore: Revert "feat: set default output for sources (#1453)""

go.mod, go.sum
* feat: java - support x-speakeasy-error-message
* feat: java - enhance equals/hashCode to support mathematical equivalence
* feat: python error handling 2.0
* fix: java toolchain language version in build.gradle
* fix: Skip templating MCP Server scope flag and property when MCP scopes are unused
=> feat: Java x-speakeasy-error-message, improved equals/hashCode, and toolchain language version, Python error handling, TypeScript MCP Server CLI fixes

internal/run/criticalWarnings.go, internal/run/target.go
This PR adds a warning in the final warning box when compilation is skipped.
=> feat: Add warning when compilation is skipped

go.mod, go.sum
This PR introduces conditional compilation guards around Sorbet type annotations and provides fallback type system implementations to make Sorbet an optional dependency.
=> feat: Make Sorbet dependency optional via conditional compilation guards

cmd/root.go
=> chore: Add MCP Servers to bullet points in Speakeasy --help

cmd/quickstart.go, prompts/configs.go, prompts/target_form_field.go, prompts/target_form_fields.go
This pull request improves the `speakeasy quickstart --mcp` with better wording.
=> feat: improved the quickstart mcp flow

cmd/repro.go, cmd/repro_test.go, cmd/root.go, integration/quickstart_test.go, internal/run/run.go, internal/run/source.go, internal/run/sourceTracking.go, internal/run/workflow.go, internal/sdkgen/sdkgen.go, internal/testutils/testutils.go
Enable customers to provide a one line command for reproducing any issue they may face.
=> feat: `speakeasy repro`

go.mod, go.sum
- SSE not consuming entire stream
- move enums to top of models to avoid dependency errors and add warning for invalid enum defaul
=> fix: issue in typescript consuming full sse streams

go.mod, go.sum
This change provides support for the `x-speakeasy-token-additional-properties` for Go.
=> feat(go): support x-speakeasy-token-endpoint-additional-properties

integration/quickstart_test.go
Reference: https://linear.app/speakeasy/issue/GEN-1698/tech-debt-parallelize-integration-testquickstart-testing
Previously:
```console
$ go test -count=1 -run=TestQuickstart -v ./integration
...
ok  	github.com/speakeasy-api/speakeasy/integration	356.123s
```
Now:
```
$ go test -count=1 -run=TestQuickstart -v ./integration
...
ok  	github.com/speakeasy-api/speakeasy/integration	83.006s
```
=> chore: Parallelize quickstart integration testing

go.mod, go.sum
add python and typescript implementation for x-speakeasy-token-endpoint-additional properties
=> feat: support x-speakeasy-token-endpoint-additional-properties for ts and py

prompts/targets.go
Fixes quickstart so that the "target group" and "target selection" pages are shown sequentially rather than simultaneously.
https://github.com/user-attachments/assets/59d28b47-aed9-4b07-b373-5f27b1f13e98
=> fix: quickstart "target group" and "target selection" shown sequentially rather than simultaneously

go.mod, go.sum
https://github.com/speakeasy-api/openapi-generation/releases/tag/v2.714.0
=> feat: allow generation of sync, async or both methods in a python sdk

go.mod, go.sum
fix(python): generated code samples sdk import in async split mode
> https://github.com/speakeasy-api/openapi-generation/pull/3242
fix: handle nullable discriminated unions deserialization C#
> https://github.com/speakeasy-api/openapi-generation/pull/3232
=> fix: nullable unions C#; pythonV2 async split code samples

cmd/run.go, internal/run/dependent.go, internal/run/source.go, internal/run/target.go
- Dependents will now see their `out.openapi.yaml` files updated to reflected the input spec
- Dependents can now be run from anywhere in the project
=> feat: Improvements to `dependents` workflow
